### ISSUE TITLE
app_options 的 vim_mode 选项对 com.sublimetext.4 是否有效？

### ISSUE THREAD

**Issue by jiapeng123456** [rime/squirrel#1000]
自己测试了一下app_options 的 vim_mode的功能。
经过测试 app_options 的 vim_mode 对 iterm2 是有效的，但对 com.sublimetext.4 感觉是无效的。
请问一下，是没有对 com.sublimetext.4 做兼容，还是我个人设置的问题？
**環境**
 - 系統版本： (macOS 14.7)
 - 鼠鬚管版本： (0.16.0)

下面是我的配置：
```
patch:
  app_options:
    com.google.Chrome:
      ascii_mode: true
    com.microsoft.VSCode:
      ascii_mode: true
    com.apple.dt.Xcode:
      ascii_mode: true
    org.yuanli.utools:
      ascii_mode: true
    com.apple.Terminal:
      ascii_mode: true
    com.googlecode.iterm2:
      ascii_mode: true  # 初始爲西文模式
      no_inline: true   # 不使用行內編輯
      vim_mode: true    # 退出VIM插入模式自動切換輸入法狀態
    com.apple.finder:
      ascii_mode: true
    com.sublimetext.4:
      ascii_mode: true  # 初始爲西文模式
      no_inline: true   # 不使用行內編輯
      vim_mode: true    # 退出VIM插入模式自動切換輸入法狀態
    com.sublimetext.3:
      ascii_mode: true  # 初始爲西文模式
      no_inline: true   # 不使用行內編輯
      vim_mode: true    # 退出VIM插入模式自動切換輸入法狀態
    com.apple.calculator:
      ascii_mode: true
    com.apple.launchpad.launcher:
      ascii_mode: true
    com.apple.systempreferences:
      ascii_mode: true
    com.apple.ActivityMonitor:
      ascii_mode: true
    com.apple.keychainaccess:
      ascii_mode: true
    com.apple.Spotlight:
      ascii_mode: true
    com.jetbrains.intellij:
      ascii_mode: true  # 初始爲西文模式
      no_inline: true   # 不使用行內編輯
      vim_mode: true    # 退出VIM插入模式自動切換輸入法狀態

```
