### ISSUE TITLE
无法启用caps_lock切换英文输入法并且小写

### ISSUE THREAD

**Issue by evindu** [rime/squirrel#101]
我根据官方教程 设置 default.custom.yaml       ascii_composer/good_old_caps_lock: false
    Caps_Lock: commit_code  但是按下caps_lock 仍然是大写 怎么改成和mac自带中文一样caps_lock 是切换英文输入法并且小写？

这是我的yaml文件
patch:
  switcher:
    caption: 〔方案选单〕
    hotkeys:
    - Control+grave
  #下面定义中英文切换的方式
    ascii_composer/good_old_caps_lock: false
    ascii_composer/switch_key:
    Caps_Lock: commit_code
    Return: commit_code
    Eisu_toggle: clear
    Shift_L: commit_text
    Shift_R: inline_ascii

**Comment by lotem** [comment]
貼出的代碼沒有縮進。如果錄入正確，可以奏效。
參見引用多行代碼的 Markdown 語法：
https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by evindu** [comment]
@lotem 
![](http://i3.buimg.com/ba12e53be746f577.png)

**Comment by iugo** [comment]
@lotem 我也有此問題, 如下設置, 並且重新部署後無效.

想要達到的效果爲單擊 Shift_L 不要切換中英文, 只有在 Caps_Lock 按下之後再切換中英文.

```
# squirrel.custom.yaml
# encoding: utf-8

patch:
  ascii_composer/good_old_caps_lock: false
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
```
