### ISSUE TITLE
如何设置第10个序号显示“0”

### ISSUE THREAD

**Issue by BOSSDAI** [rime/squirrel#1011]
现在我的第10个序号显显的是“10”：
<img width="244" alt="Screenshot 2025-01-11 at 6 04 57 PM" src="https://github.com/user-attachments/assets/95a532d0-eb5b-41a5-b28e-13d3a3a432c7" />
我更希望显示的是“0”，这个有办法设置吗？

**Comment by BOSSDAI** [comment]
已经解决，不过有点奇怪。
在`menu`中添加
```
alternative_select_keys: "1234567890"
```
目前我的设置：
```
patch:
    ....
    # Menu
    menu:
      page_size: 10 
      # alternative_select_labels: [ ①, ②, ③, ④, ⑤, ⑥, ⑦, ⑧, ⑨, ⑩ ]
      alternative_select_keys: "1234567890"
```
说奇怪是因为，感觉上这个应该由`alternative_select_labels`控制，实际上是由`alternative_select_keys`控制，`alternative_select_labels`似乎不起任何作用
