### ISSUE TITLE
新版更新了“数字后标点优化”，如何不启用这个优化？

### ISSUE THREAD

**Issue by zhjh0521** [rime/squirrel#1019]
在中文输入中，已经习惯数字后跟中文的逗号，新的版本是英文的逗号，而且有个下划线。如何通过punctuator/digit_separators来禁止这个新功能？

**Comment by LEOYoon-Tsaw** [comment]
設為空字符串應能停用

**Comment by lotem** [comment]
任改點兒什麼都會收到意想不到的用家的意見。看來 Rime 用家數量不少！

**Comment by lotem** [comment]
``` yaml
# 方案.custom.yaml
# 默認是數字之後認這四種符號
patch:
  punctuator/digit_separators: ",.:'"
```
