### ISSUE TITLE
中文状态下如何配置输入英文标点"`"

### ISSUE THREAD

**Issue by Edenharder** [rime/squirrel#102]
自己虽然修改了default.custom.yaml文件，对朙月拼音·简化字可以了，但对朙月拼音每次点击"`"会提示输入笔画。类似的还有小鹤双拼。

请问，在哪里修改可以关闭输入笔画的提示？自己更多的情况是想直接输入英文的标点"`"。

**Comment by scomper** [comment]
可参考配置 https://www.v2ex.com/t/303479

**Comment by lotem** [comment]
去掉這一行，就可以了
https://github.com/rime/brise/blob/master/preset/luna_pinyin.schema.yaml#L110

```yaml
# luna_pinyin.custom.yaml
patch:
    recognizer/patterns/reverse_lookup: {}
```
