### ISSUE TITLE
请问一下在切换“中文”，“西文”的时候，这个显示的“西文”是在哪里可以配置的，我看旧版本是显示的“英”

### ISSUE THREAD

**Issue by haosdent** [rime/squirrel#1024]
您好，请问切换中西文输入的时候，我用新版本显示的是“西文”，但旧版本是“英”只有一个字；
请问这个是在哪里可以控制显示的文字，还是只能回退到旧版本

**Comment by lotem** [comment]
"英” 可能是方案裏自定義的。

舊版本顯示固定的文字「中」或「A」。新版本改爲顯示方案裏定義的文字，這個預設的拼音方案裏寫作「中文」「西文」

https://github.com/rime/rime-luna-pinyin/blob/c5d3863062910a02d29761d0228ced3809afc0ac/luna_pinyin.schema.yaml#L23

方案裏除了寫 `states` 定義全稱，還可以添加 `abbrev` 定義各個狀態的簡寫。
比方說要還原舊版本的樣式，方案可以做如下定義：

```yaml
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
    abbrev: [ 中, A ]
```
