### ISSUE TITLE
[Bug] github issue栏中打字会出现多余字符

### ISSUE THREAD

**Issue by ArkURL** [rime/squirrel#1037]
**簡要描述 Bug：**
在github issue中使用rime打字，会遇到如视频展示问题，会出现多余字符

https://github.com/user-attachments/assets/8957960a-da8d-4419-9447-4e1d32efe4e3

**預期行爲：**
正常打字，不出现多余字符

**實際行爲：**
输出字符中第一个ime字母被保留输出

**環境**
 - 系統版本： (macOS 14.6.1)
 - 鼠鬚管版本： (1.0.3)
 - 方案： rime-config(mac),链接：https://github.com/Lucius-Wang/rime-config
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by mcwq123** [comment]
我也是遇到相同的情況，問題比較困擾這段時間。

**Comment by lotem** [comment]
可以復現問題。

臨時的解法：設置 `style/inline_preedit: false`

```yaml
# squirrel.custom.yaml
patch:
  style/inline_preedit: false
  app_options:  # 我用全局設置，也可以分 app 設置
```
