### ISSUE TITLE
可否把英文输入做成一个单独的输入方案？

### ISSUE THREAD

**Issue by uqiu** [rime/squirrel#1039]
我现在rime里装了两个输入方案，一个日文和一个双拼。
我想追加一个独立的英文输入方案，然后给这三个输入方案，分别分配不同的组合按键，这样实现幂等化的切换操作。
比如

- 日文 = ctrl + alt + t
- 双拼 = ctrl + alt + y
- 英文 = ctrl + alt + r

这是英文输入方案，是一个纯英文的输入方案，不需要词典词库，就是和ascii_mode的英文模式一样，敲一个字母，就马上可以上屏一个字母。

请问这个可以实现么？

**Comment by uqiu** [comment]
搞定了,从薄荷输入法那里随便高了一个五笔输入法的scheme,然后把这个输入法的这个部分设定了,就行了.

```
switches:
  - name: ascii_mode
    states: [ 中文, 英文 ]
    reset: 1
```
