### ISSUE TITLE
开发版的「罕见字过滤」失效

### ISSUE THREAD

**Issue by placeless** [rime/squirrel#120]
编译的最新开发版鼠须管，发现无论是全拼还是双拼，「罕见字过滤」都不起作用了，未知同为开发版的用户，有没有遇到同样的问题？

```yaml
# double_pinyin_flypy
patch:

  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: extended_charset
      states: ["通用", "增廣"]
    - name: simplification
      reset: 1  # 增加這一行：默認啓用「繁→簡」轉換。
      states: ["漢字", "汉字"]
    - name: ascii_punct
      states: ["。，", "．，"]

  # translator/preedit_format: {}     # 输入双拼码的时候不转化为全拼码
  recognizer/patterns/reverse_lookup: # 关闭 ` 键反查功能

  # 启用罕见字過濾
  engine/filters:
    - simplifier
    - uniquifier
    - cjk_minifier
  translator/enable_charset_filter: true
```

**Comment by placeless** [comment]
基本解决了我自己的问题。
之前，打 `ha`、`kai` 等拼音时，有许多问号出来，感觉「罕见字过滤」未起作用，后来做了两件事：

1. 将 `translator/dictionary: luna_pinyin` 改为了 `translator/dictionary: pinyin_simp`，减少不常用的单字。以 `kai` 为例，luna_pinyin 内含 86 个单字，其中 21 个显示不出来，表现为 `？`号；而 `pinyin_simp` 只有 28 个，且默认（在 sublime text 内）都能正常显示。
2. 做完第一步之后，还有个别文字在候选区显示为`？`，比如 `開`。于是又将 `switches` 的「繁→簡」转换，由 `name: simplification` 改为 `name: zh_simp`，，并且将 `engine/filters:` 内 `simplifier` 改为 `simplifier@zh_simp`

最终的 patch 如下，不再用到 `cjk_minifier` 和 `translator/enable_charset_filter`：
```yaml
# double_pinyin_flypy.custom.yaml, 只对小鹤双拼生效
patch:
  schema/dependencies:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: zh_simp    # ※ 第二处
      reset: 1
      states: [ 漢字, 汉字 ]
    - name: ascii_punct
      states: ["。，", "．，"]

  engine/filters:
      - simplifier@zh_simp        # ※ 第二处
      - uniquifier
  translator/dictionary: pinyin_simp    # ※ 第一处
```
