### ISSUE TITLE
[提案] app_options 参数设定追加 esc 自动切换 ascii_mode 选项

### ISSUE THREAD

**Issue by erasin** [rime/squirrel#124]
在配置文件 squirrel.yaml 中有

```
org.vim.MacVim: 
    ascii_mode: true 
org.microsoft.VSCode:
    ascii_mode: true 
```

macvim 貌似 'imd' 支持了 esc 触发自动切换回英文状态。 而vscode等则不会自动切换。 
在mac编辑器时经常使用 `vim` 模式， esc 退出编辑模式时候还是需要使用 `shift` 才能切换到英文模式输入命令。 

如果增加配置选项 `ascii_esc: true` 来使特定的软件内输入法支持 esc 自动切换到英文模式就方便多了。

```
org.vim.MacVim: 
    ascii_mode: true 
    ascii_esc: true
org.microsoft.VSCode:
    ascii_mode: true 
    ascii_esc: true
```

> 实际上还有一种全局热键的设定esc为切换到ascii_mode ，
> 编辑文件 `default.yaml` 找到节点 `key_binder: bindings:` 追加内容
> `- { when: always, accept: Escape, toggle: ascii_mode }`
> 这样会导致vim中需要两次来切换模式，第一次为输入法切换，第二次为模式切换，有的时候一次切换完成。。。
> 我不清楚在设置快捷键的具体设置的方法，如何将这两次合并为一次？（追加send貌似不起作用）
