### ISSUE TITLE
VSCode编辑器配置ascii_mode静默模式无效，配置其他应用中英状态切换均正常

### ISSUE THREAD

**Issue by y2kbug** [rime/squirrel#141]
贴上配置ascii_mode代码，系统 macOs 10.11.6  vscode 1.8.1 鼠须管是最新手动编译的
```
app_options/com.googlecode.iterm2:
        ascii_mode: true
      app_options/com.tdesktop.Telegram: {}
      app_options/com.tencent.qq: {}
      app_options/com.microsoft.VSCode:
        ascii_mode: true
      app_options/com.runningwithcrayons.Alfred-2:
        ascii_mode: true
```
