### ISSUE TITLE
可以修改切换输入法时变成英文上屏吗？

### ISSUE THREAD

**Issue by bytanuky** [rime/squirrel#146]
通过源码直接编译的最新版，发现鼠须管打字中途切换输入法，会让中文直接上屏，而系统自带中文输入法是英文直接上屏，这个有办法修改吗？

**Comment by mrtanuky** [comment]
![](http://i.imgur.com/4UI8BXj.png)

在这种情况下切换输入法，系统自带中文输入法上屏的是“ceshi”，而鼠须管上屏的是“测试”

**Comment by xdidi3r** [comment]
我也有这个需求，还找不到方法解决

**Comment by mrtanuky** [comment]
刚才调试了一下，发现切换输入法及切换到其他窗口时都会调用deactivateServer()，有没有办法修改一下这呢

**Comment by funemy** [comment]
@xdidi3r @mrtanuky 
在`default.custom.yaml`文件中，加入如下设置即可(假设切换中英文使用`shift`建)
```
patch:
  ascii_composer:
    switch_key:
      Shift_L: commit_code
      Shift_R: commit_code
```
