### ISSUE TITLE
请问如何设置调用alfred3时自动切换为英文状态

### ISSUE THREAD

**Issue by northleafup** [rime/squirrel#154]
以下的这个设置不起作用啊
app_options:
  com.alfredapp.Alfred:
    ascii_mode: true
  com.runningwithcrayons.Alfred-3:
    ascii_mode: true

请问该如何设置才能起作用呢，谢谢！

**Comment by Voleking** [comment]
squirrel.custom.yaml 里面
```
patch:
  app_options:
    com.runningwithcrayons.Alfred-3:
      ascii_mode: true
```
