### ISSUE TITLE
shift 组合键 出现不希望的中英文切换

### ISSUE THREAD

**Issue by seudut** [rime/squirrel#161]
不知道大家有没有这样的问题，我设置 <kbd>Shift</kbd> 为中英文切换
```
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_code
````
但是有时当我按 <kbd>Shift + f</kbd> 想输入 <kbd>F</kbd>的时候，也会中英切换。这种情形发生在 Firefox 的插件 vimperator 中。

同样的问题，如果设置 <kbd>Ctrl</kbd> 为中英切换，当按下 <kbd>Ctrl + h</kbd> 是也会中英切换。这种情形出现在 emacs 中。

显然，当我们按下组合键 <kbd>Shift +  </kbd>，或者是 <kbd>Ctrl +  </kbd>，的时候，我们是不希望 rime 中英切换的。不知道 rime 能不能处理这样的问题
