### ISSUE TITLE
control键单击时冲突？

### ISSUE THREAD

**Issue by 3xp10it** [rime/squirrel#163]
系统：macOS sierra
程序：MacVim (console)
键盘：HHKB PRO BT
相关设置如下：
```
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: inline_ascii
    Shift_R: commit_text
config_version: 0.36.custom.796813850
customization: 796813850
key_binder:
  bindings:
    - {accept: Escape, toggle: ascii_mode, when: always}

```
问题：
在系统中用keyboard maestro工具设置好了control键的功能为“按一下control为esc，按住control为control",在macvim中insert模式下按一下contrl没有转到正常模式,请问是不是我的设置有问题导致control失效？

ps：
1.上面的`- {accept: Escape, toggle: ascii_mode, when: always}`解决了按下esc自动切换到英文输入的问题
2.试过在百度五笔输入法下没有这个问题
