### ISSUE TITLE
如何输入数学公式比如N的平方

### ISSUE THREAD

**Issue by northleafup** [rime/squirrel#170]
我目前使用的是鼠须管的五笔86模式，请问如何输入数学公式，比如平方

**Comment by winduser** [comment]
你可以用 `/sb` 和 `/xb` 来实现简单的数学公式。更多特殊符号的输入，可以参考鼠须管目录下的 `symbols.yaml`。

**Comment by northleafup** [comment]
@winduser  您好，请问为何我输入n/sb3没有效果呢?是我哪里输的不对么，谢谢！

**Comment by winduser** [comment]
`n³`，我能正常输入。你是否在鼠须管的输入框内输入了`/sb`？

**Comment by northleafup** [comment]
@winduser 您好，现在我的已经可以了，是配置的问题，我本机的wubi_pinyin.custom.yaml文件配置内容如下：
`yaml
patch:
  schema/dependencies:
    - emoji
  reverse_lookup:
    dictionary: emoji
    enable_completion: false
    prefix: "`"
    tips: 〔表情〕
  punctuator:
    import_preset: symbols
  recognizer:
    import_preset: default
    patterns:
      reverse_lookup: "`[a-z]*'?$"
      punct: "^/([a-z]+|[0-9]0?)$"
`

**Comment by northleafup** [comment]
@winduser 您好，现在我的已经可以了，是配置的问题，我本机的wubi_pinyin.custom.yaml文件配置内容如下：
```
patch:
  schema/dependencies:
    - emoji
  reverse_lookup:
    dictionary: emoji
    enable_completion: false
    prefix: "`"
    tips: 〔表情〕
  punctuator:
    import_preset: symbols
  recognizer:
    import_preset: default
    patterns:
      reverse_lookup: "`[a-z]*'?$"
      punct: "^/([a-z]+|[0-9]0?)$"
```
