### ISSUE TITLE
和安装有关的一点问题

### ISSUE THREAD

**Issue by 5cylinders** [rime/squirrel#175]
必须先感谢佛振的工作。我是郑码用户，被windows虐待了许多年，一直不能换用mac，就是因为Mac下没有好用的郑码输入法，直到发现了鼠须管，才在四年前变换阵营。
我用的是0.9.26.1。早知有0.9.26.2，迟迟不敢更新，因为当初配置郑码颇花力气，生怕重新安装后出差池，——尽管知道备份自己的用户文件，但还是战战兢兢，因为输入法对我太重要了。
问题1：新编译的APP能否直接覆盖？（我解开PKG包看过，里边有安装前后的两个配置环境的脚本文件，所以没敢覆盖。)
问题2:现在的安装路径是在input methods下，将来可否像别的应用那样，安装到应用程序里，而另行解决调用问题？
问题3:现在的用户设定文件有点分散，将来可否集中一点儿，便于更新时自动保存设定？

对项目一无贡献，反倒有各种奢求，自己都有点不好意思了。

**Comment by Voleking** [comment]
看许久没人回答，试着回答一下，不保证一定对:joy:
1. 可以直接覆盖旧的APP（不知道你是不是这个意思）；
2. 为什么有这样的需求
3. 备份参考我的installation.yaml，然后点 Sync User data 就可以了，网上有挺多参考的
```yaml
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.9.26.2
install_time: "Wed Jun 14 20:32:06 2017"
# installation_id: "6532cf9a-58a9-4731-9c69-fa52e8d0f2ef"
rime_version: 1.2.9
installation_id: "squirrel"
sync_dir: "/Users/Voleking/Library/Mobile Documents/com~apple~CloudDocs/Rime"
```
另官网的安装包已经很老了，参见#152，建议自行编译
