### ISSUE TITLE
无法禁用左shift或者右shift作为中英文切换，即无法区分左右shift快捷键

### ISSUE THREAD

**Issue by wandering007** [rime/squirrel#176]
我将`default.custom.yaml`配置如下以禁用右shift切换中英文：

```
patch:
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Shift_L: inline_ascii
    Shift_R: noop
    Control_L: noop
    Control_R: noop
```
但重新deploy后，右shift并没有被禁用。我尝试禁用左shift键会导致左右shift键都被禁用。
我发现搜狗输入法的配置也存在类似的问题。  
update：  
好像是我mac的问题。。。
