### ISSUE TITLE
Can't switch to chinese input on some MacOS apps.

### ISSUE THREAD

**Issue by MarloweW** [rime/squirrel#184]
Running squirrel 0.9.26.1 on MacOS 10.13.2, In some apps(Google Chrome, iTerm2) can't switch to chinese input method.

squirrel looks like this:

<img width="219" alt="screen shot 2018-01-03 at 2 35 43 pm" src="https://user-images.githubusercontent.com/9361073/34510982-6a6b7bbe-f093-11e7-8bdd-bdd3381b4a20.png">

Meanwhile, I switch to another app like Notes.app or VSCode.app, all worked.

I have two custom comfig:

```yaml
# squirrel.custom.yaml
patch:

# Style
  us_keyboard_layout: true      # 鍵盤選項：應用美式鍵盤佈局
  style/horizontal: true        # 候選窗横向顯示
  style/font_point: 14          # 字號
  style/color_scheme: native      # 選擇配色方案

# Slient Mode:
  app_options/com.apple.Xcode:
    ascii_mode: true
  app_options/com.microsoft.VSCode:
    ascii_mode: true
  app_options/com.jetbrains.pycharm:
    ascii_mode: true
  app_options/com.googlecode.iterm2:
    ascii_mode: true
  app_options/com.google.Chrome:
    ascii_mode: true
```
and 

```yaml
# default.custom.yaml
patch:
  menu/page_size: 5
```
Get crash report from console.app:

```
Process:               Squirrel [43553]
Path:                  /Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel
Identifier:            com.googlecode.rimeime.inputmethod.Squirrel
Responsible:           Squirrel [43553]
6   com.googlecode.rimeime.inputmethod.Squirrel	0x0000000104ce7967 main + 603
7   com.googlecode.rimeime.inputmethod.Squirrel	0x0000000104ce7704 start + 52
       0x104ce6000 -        0x104cf3ff7 +com.googlecode.rimeime.inputmethod.Squirrel (0.9.26.1) <A20806D6-AFA0-3679-9456-A512AF5C8415> /Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel
       0x104d02000 -        0x104f20fff +librime.1.dylib (0) <12C2695A-0F12-361D-8083-04E52C76AB38> /Library/Input Methods/Squirrel.app/Contents/Frameworks/librime.1.dylib
       0x1051bc000 -        0x1051d3fff +org.andymatuschak.Sparkle (1.5 Beta 6 - 313) <9253F8F7-250B-1114-7AE9-A10A54EB2298> /Library/Input Methods/Squirrel.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x1051ec000 -        0x10521bfff +com.growl.growlframework (1.3.1 - 1.3.1) <81F2E452-20C8-3F2D-94B2-B58FA5DE1ECE> /Library/Input Methods/Squirrel.app/Contents/Frameworks/Growl.framework/Versions/A/Growl
    0x7fff7b450000 -     0x7fff7b5e3fe7  libsqlite3.dylib (274.5) <A1DEB5AB-8FE8-332E-A7E5-F493F2223FE3> /usr/lib/libsqlite3.dylib
```
