### ISSUE TITLE
标点符号不能直接上屏

### ISSUE THREAD

**Issue by northleafup** [rime/squirrel#191]
我用的五笔拼音输入方案，为了确保能输入特殊符号，复制了一份symbols.yaml文件到my_symbols.yaml
其中自定义的wubi_pinyin.custom.yam文件内容如下：
```yaml
patch:
  schema:
    dependencies:
      - my_symbols
      - emoji
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      reset: 0
      states: ["半角", "全角"]
    - name: extended_charset
      states: ["常用", "增廣"]
      # - name: ascii_punct
      # - states: ["。，", "．，"]
  engine:
    processors:
      - ascii_composer
      - recognizer
      - key_binder
      - speller
      - punctuator
      - selector
      - navigator
      - express_editor
    segmentors:
      - ascii_segmentor
      - matcher
      - affix_segmentor@myemoji
      - abc_segmentor
      - punct_segmentor
      - fallback_segmentor
    translators:
      - punct_translator
      - reverse_lookup_translator
      - table_translator
      - script_translator@myemoji
  abc_segmentor:
    extra_tags:
      - reverse_lookup
  speller:
    auto_select: true
  key_binder:
    import_preset: default
  punctuator:
    import_preset: my_symbols
  recognizer:
    import_preset: my_symbols
    patterns:
      myemoji: "`[a-z']*;?$"
      punct: "(/[0-9]?[a-z]*)?([^a-z0-9]?)?"
      reverse_lookup: "`[a-z]*’?$"
  # 输入Emoji 以前缀`开始
  myemoji:
    # script_translator@emoji
    dictionary: emoji
    preedit_format:
      - "xform/^([a-z]*)$/【Emoji】$1/"
    # affix_segmentor@myemoji
    tag: myemoji
    prefix: '`'
    tips: 〔Emoji〕
    closing_tips: 〔Emoji〕
  reverse_lookup:
    dictionary: pinyin_simp
    preedit_format:
      - "xform/([nl])v/$1ü/"
      - "xform/([nl])ue/$1üe/"
      - "xform/([jqxy])v/$1u/"
    prefix: "`"
    suffix: "'"
    tips: "〔拼音〕"
  translator:
    dictionary: wubi86
    disable_user_dict_for_patterns:
      - "^z.*$"
    enable_charset_filter: true
    enable_encoder: true
    enable_sentence: true
    encode_commit_history: true
    max_phrase_length: 4
    prism: wubi_pinyin

```
改后的my_symbols.yaml部分内容如下：
```yaml
  half_shape:
    " ": {commit: " "}
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": "＃"
    "$": "￥"
    "%": "％"
    "&": "＆"
    "'": {pair: ["‘", "’"]}
    "(": {commit: "（"}
    ")": "）"
    "*": ["*", "＊", "·", "・"]
    "+": "＋"
    ",": {commit: "，"}
    "-": "－"
    ".": {commit: "。"}
    "/": ["、", "/", "／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": "《"
    "=": "＝"
    ">": "》"
    "?": {commit: "？"}
    "@": "@"
    "[": {pair: ["【", "「"]}
    "\\": "、"
    "]": {pair: ["】", "」"]}
    "^": {commit: "……"}
    _: "——"
    "`": "｀"
    "{": "｛"
    "|": "｜"
    "}": "｝"
    "~": "～"
```
我的问题是这样的： 针对 “。” 符号，当输入“.”时自动上屏“。”，可是每一次输入时都需要选择后才能上屏，也即不能自动上屏，请问这个是什么原因？谢谢。

**Comment by lotem** [comment]
这改动太多了。能否先定位到引发问题的具体代码？

**Comment by northleafup** [comment]
@lotem 您好，我的问题重点出在my_symbols.yaml文件上，根据鼠须管的提示，如果标点符号后接commit会自动上屏的，但是我以下的代码并不起作用，还请麻烦查一下，谢谢。相关的代码如下：
以下为wubi_pinyin.custom.yaml文件的相关代码
```yaml
punctuator:
    import_preset: my_symbols
  recognizer:
    import_preset: my_symbols
    patterns:
      myemoji: "`[a-z']*;?$"
      punct: "(/[0-9]?[a-z]*)?([^a-z0-9]?)?"
      reverse_lookup: "`[a-z]*’?$"
```
my_symbols.yaml相关代码如下:
```yaml
half_shape:
   # 此处略去一些标点
   # 按照文档的配置，以下代码应该是可以自动上屏的
    ".": {commit: "。"}
   # 此处略去一些标点
```
