### ISSUE TITLE
启用双拼后，部署过程中 crash，不显示汉字

### ISSUE THREAD

**Issue by mpco** [rime/squirrel#192]
我按照 INSTALL.md 中的步骤安装：

1. brew install cmake boost
2. git clone ...
3. make deps
4. make
5. sudo make install

此时，部署正常，输入正常。

为了使用双拼方案，运行：

```
cd brise
bash rime-install
```

然后，新建 default.custom.yaml 文件：

```
# Rime custom settings
# encoding: utf-8

patch:
  schema_list:
    - schema: double_pinyin_flypy
    - schema: luna_pinyin
    - schema: emoji
  switcher/caption: "/方案菜单/"
  switcher/hotkeys: 
    - "Control+Shift+grave"
```

重新部署，切换至双拼后，输入时只显示输入的字母，不显示全拼和汉字。

[Squirrel_2018-03-07-223732.txt](https://github.com/rime/squirrel/files/1789542/Squirrel_2018-03-07-223732_M-macOS.txt)

请问怎么解决？ 是什么原因呢？
