### ISSUE TITLE
default.custom.yaml 似乎不生效

### ISSUE THREAD

**Issue by EonYang** [rime/squirrel#197]
在`default.custom.yaml`， 我写下了：
```
ascii_composer:
  switch_key:
    Control_L: commit_code
```

在`default.yaml`， 我没有做任何改动，所以默认有如下配置：
```
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: inline_ascii
    Shift_R: commit_code
```

在我理解中，我的`default.custom.yaml`会直接覆盖掉`default.yaml`，所以按下`Control_L`应当可以切换ascii模式。

但是我按`Control_L`的时候什么也没有发生，直到我把配置写入`default.yaml`。
