### ISSUE TITLE
Eisu_toggle 映射不生效

### ISSUE THREAD

**Issue by EonYang** [rime/squirrel#211]
### 为了让按下Caps_lock等同于按下Shift，我进行了如下配置：

1. 定义  Eisu_toggle 为 commit_code ：

```
# default.custom.yaml
patch:

  ascii_composer/switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: commit_code
    Shift_L: commit_code
    Shift_R: noop
```
2. 映射Caps_Lock到Eisu_toggle 

![image](https://user-images.githubusercontent.com/9332910/39464011-25240780-4ce9-11e8-9549-a568f72b4406.png)

3. 验证，按下Caps_Lock会trigger Eisu_toggle（lang2）：

![image](https://user-images.githubusercontent.com/9332910/39464041-42dc75aa-4ce9-11e8-8444-4376fcbdcf55.png)

### 期待结果

当按下键盘上的Caps_lock, 机器监听到触发Eisu_toggle（key code 0x91）, RIME在中文模式和ascii mode 间切换。

### 实际情况

按Caps_Lock什么也不发生。
