### ISSUE TITLE
简体过滤问题

### ISSUE THREAD

**Issue by Voleking** [rime/squirrel#213]
简体时输入`zhou`时会出现两个相同的周：
![screen shot 2018-05-15 at 9 23 18 pm](https://user-images.githubusercontent.com/13161779/40059283-50783f02-5886-11e8-9b54-9114070dce01.png)
貌似是週变为简体时未能成功过滤掉：
![screen shot 2018-05-15 at 9 23 06 pm](https://user-images.githubusercontent.com/13161779/40059344-6a953a5c-5886-11e8-976a-9261a1fb9c2d.png)
可能相关配置`luna_pinyin_simp.custom.yaml`：
```yaml
patch:
  simplifier:
    option_name: zh_simp

  engine/filters:
      - simplifier
      - uniquifier
      - charset_filter@gbk              # (※3) GBK 过滤
      - single_char_filter
      - simplifier@emoji_conversion
```

**Comment by lotem** [comment]
靠以上配置無法重現

**Comment by Voleking** [comment]
将`simplifier@emoji_conversion` 提至 `uniquifier` 前解决问题，其中 opencc 文件夹内容与[OpenCC_Emoji](https://github.com/rime-aca/OpenCC_Emoji) 项目文件中内容相同，全部配置如下：
```yaml
patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: zh_simp                      # (※1) 繁简转换
      reset: 1
      states: ["漢字", "汉字"]
    - name: ascii_punct
      states: ["。，", "．，"]
    - name: show_emoji
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
    - options: ["utf8", "gbk", "gb2312"] # (※2)字符集选单
      reset: 0                           #     默认 UTF8
      states:
        - UTF-8
        - GBK
        - GB2312
        
  simplifier:
    option_name: zh_simp

  engine/filters:
      - simplifier
      - simplifier@emoji_conversion
      - uniquifier
      - charset_filter@gbk              # (※3) GBK 过滤
      - single_char_filter

  emoji_conversion:
    opencc_config: emoji.json
    option_name: show_emoji
    # tips: all
```
