### ISSUE TITLE
inline_preedit 有时会失效

### ISSUE THREAD

**Issue by antonchen** [rime/squirrel#234]
设置了 `inline_preedit: true` 但是有时候会失效变成多行模式（如下图），切换一下输入法就好了，一天会出现好几次。有没有知道原因的？

![image](https://user-images.githubusercontent.com/9129579/44695538-3da02a80-aaa6-11e8-9eeb-85a56a1ad893.png)

**看日志也没有什么特别的，不知道怎么设置日志级别 Debug**  
我的 squirrel.custom.yaml

```yaml
patch:
  show_notifications_when: appropriate

  style/color_scheme: system_blue
  preset_color_schemes:
    system_blue:
      name: "系统蓝／System Blue"
      author: "Scomper <scomper@gmail.com>"
      font_face: "PingFang SC,HanaMinA"
      back_color: 0xFFFFFF
      border_color: 0xE0B693
      candidate_text_color: 0x000000
      comment_text_color: 0x999999
      hilited_back_color: 0xEE6E00
      hilited_candidate_text_color: 0xFFFFFF
      hilited_candidate_label_color: 0xFFFFFF
      hilited_comment_text_color: 0x999999
      hilited_text_color: 0x999999
      text_color: 0x000000
      label_color: 0x999999
      label_font_face: "SFCompactText-Regular"

      horizontal: true
      inline_preedit: true
      candidate_format: "%c\u2005%@ \u2005"
      font_point: 16
      label_font_point: 14
      corner_radius: 5
      border_height: 0
      border_width: 0
```
