### ISSUE TITLE
双拼模式下怎么能不让输入框的拼音自动展开成全拼？

### ISSUE THREAD

**Issue by google9002** [rime/squirrel#261]
比如我现在在用小鹤双拼，打拼音两个字是pb yb，但是输入框会自动给我改成全拼pin yin，然后如果直接按回车，出来的依然是pb yb，这个过程我觉得很反逻辑，我希望能够在输入框显示pbyb，该怎么操作？

**Comment by lotem** [comment]
用這個補靪：
```yaml
# double_pinyin_flypy.custom.yaml
patch:
  translator/preedit_format: []
```
