### ISSUE TITLE
0.11.0版和倉頡5在BBEdit鍵入中文的問題

### ISSUE THREAD

**Issue by iPopper** [rime/squirrel#301]
又碰到一個問題。
0.11.0版，倉頡5在BBEdit鍵入中文時，每字輸入後游標都會往前跑，游標前移的位置每次不一定。
不過朙月拼音可以正常鍵入。
0.9.26.2版沒這個問題。
（macOS 10.14.3, BBEdit 12.5.2）

不知是鼠鬚管還是倉頡5的問題？

**Comment by flyingns** [comment]
同样的问题，有解吗？

**Comment by lotem** [comment]
默認配置組詞狀態的光標後顯示對應倉頡碼，可能該編輯器不能正確處理這種情況。
可以通過以下配置去掉倉頡碼：
```yaml
# cangjie5.custom.yaml
patch:
  translator/preedit_format: []
```
