### ISSUE TITLE
请问明月拼音如何配置联想输入？目前我这边只能使用全拼输入

### ISSUE THREAD

**Issue by truebit** [rime/squirrel#319]
如题，自己看了些配置文件，组装出来了一个简体版本的输入。
但是不能做联想输入：比如`shenm`自动出现“什么”，`zaim`出现“在么”这种

**Comment by lotem** [comment]
根據描述，問題並非出現在原裝的朙月拼音輸入方案，而是未知的用戶自製方案。

朙月拼音的用法：從方案選單切換爲簡化字模式
https://github.com/rime/home/wiki/UserGuide#%E7%B9%81%E7%B0%A1%E5%AD%97%E5%88%87%E6%8F%9B

**Comment by truebit** [comment]
感谢回复。请问具体是哪个选项控制联想效果的呢？

**Comment by truebit** [comment]
这是我的配置方案：
```yaml
patch:
  schema/dependencies: {}
  schema/name: 明月拼音·简体
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: emoji_suggestion
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: zh_simp
      reset: 1
      states: [ 漢字, 汉字 ]
    - name: ascii_punct
      states: [ 。，, ．， ]
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
  # engine/translators:
  #   - punct_translator
  #   - script_translator
  engine/filters:
    - simplifier
    - simplifier@emoji_suggestion
    - uniquifier
  reverse_lookup:
    dictionary: stroke
    enable_completion: true
    prefix: "`"
    suffix: "'"
    tips: 〔筆畫〕
    preedit_format:
      - xlit/hspnz/一丨丿丶乙/
    comment_format:
      - xform/([nl])v/$1ü/
  punctuator:
    import_preset: symbols
  recognizer:
    import_preset: default
    patterns:
      punct: "^/([a-z]+|[0-9]0?)$"
      html: "^<[a-z]+>$"
      camel: "[a-z]+[A-Z].*$"
      url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]{1,11}[.:_-].*$"
  speller/algebra:
    - "erase/^xx$/"
    # 設置模糊音
    - "derive/^([nl])ve$/$1ue/"
    - "derive/[zg]([iv])/j$1/"
    - "derive/[ck]([iv])/q$1/"
    - "derive/[sh]([iv])/x$1/"
    - "derive/^([jqxy])v/$1u/"
    - "derive/([zcs]h|r)ii$/$1i/"
    - "derive/m$/n/"
    - "derive/ia([mn])$/ie$1/"
    - "derive/([bpmfw])ong/$1eng/"
    - "derive/un$/uen/"
    - "derive/ui$/uei/"
    - "derive/iu$/iou/"
    # 纠错
    - "derive/([aeiou])ng$/$1gn/"
    - "derive/([dtngkhrzcs])o(u|ng)$/$1o/"
    - "derive/ong$/on/"
    - "derive/ao$/oa/"
    - "derive/([iu])a([ou]|ng?)$/a$1$2/"
    # 简拼
    - abbrev/^([a-z]).+$/$1/
    - abbrev/^([zcs]h).+$/$1/
  ## 词典
  translator:
    dictionary: luna_pinyin.extended
    prism: luna_pinyin_simp
    # enable_correction: true
  
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase
    db_class: stabledb
    enable_completion: false
    enable_sentence: false
    initial_quality: 1
```
