### ISSUE TITLE
phpStorm 中 cap 切换中英文无效 

### ISSUE THREAD

**Issue by KyleBing** [rime/squirrel#349]
已经在 `default.custom.yaml` 中配置了 `cap` 用于切换中英文

```yaml
  ascii_composer:
    good_old_caps_lock: false       # true: 在保持 cap 键原有的特征， false: 点击不会切换大小写
    switch_key:
      Caps_Lock: commit_code        # 如果想用 cap 键切换中英文输入，就修改为上面三种的任一一种，否则用 noop
      Shift_L: commit_code          # macOs 上 shift 键不区别左右，设置参数同上
      Shift_R: commit_code
      Control_L: noop
      Control_R: noop
```

但在 phpStrom 中使用的时候，按 cap 能切换中英文，但还是会输出大写，也就是说 `good_old_caps_lock` 在 phpstorm 中不起作用。

这是 phpstorm 对 cap 键作了特殊的处理，还是输入法的问题？

**Comment by aLibeccio** [comment]
在 idea 中遇到了同样的问题，在其他编辑器按 cap 就能正常切换为英文小写。
我的 `default.custom.yaml` 为：
``` yaml
patch:
  ascii_composer/good_old_caps_lock: false
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
```
