### ISSUE TITLE
如何对不同的程序, 标点使用全角或半角

### ISSUE THREAD

**Issue by issuessss** [rime/squirrel#357]
例如在程序a里打字, 标点用半角,也就是英文标点.
在程序b里打字,标点用全角,也就是中文标点。
希望可以自己设置。

**Comment by GJRobert** [comment]
可能可以在 squirrel.custom.yaml 內設定：
```
patch:
  ...
  app_options:
    com.apple.Terminal:			# 那個程式的 bundle ID，這邊以 Terminal 為例
      ascii_mode: true				# 預設打出英文，這個選項一定可以用，因為一般的線上說明多半有提到這個
      ascii_punct: true				# 這是我今天幫您試的，這樣設定似乎有用，預設打出半形標點
      simplification: true			# 同理，似乎也可設定預設打出簡化字
```

若要找出特定程式的 bundle ID，可參考此文：[Easily see any app’s bundle identifier | The Robservatory](https://robservatory.com/easily-see-any-apps-bundle-identifier/)
