### ISSUE TITLE
在 IntelliJ IDEA 中，good_old_caps_lock: false 沒有作用

### ISSUE THREAD

**Issue by hiking93** [rime/squirrel#365]
嘗試修改成使用 caps lock 切換中西文，大多數 apps 沒有問題，但在 IntelliJ IDEA / Android Studio 中， `good_old_caps_lock: false` 失去作用，輸入的西文仍然是大寫。

```
# default.custom.yaml
patch:
  ascii_composer:
    good_old_caps_lock: false
    switch_key:
      Caps_Lock: commit_code
      Shift_L: noop
      Shift_R: noop
```

在 Mac 原生輸入法按 caps lock 是直接切換到「英文（美國）」或「字母」的輸入法，不知第三方輸入法如鼠鬚管能不能實現這樣的模式？
