### ISSUE TITLE
*.custom.yaml 可以設定 switches 在選單裡的 states，但改不掉 key toggle 的提示文字

### ISSUE THREAD

**Issue by GJRobert** [rime/squirrel#368]
比方 liur.schema.yaml [這個方案](https://github.com/ianzhuo/rime-liur)，裡面有
```
switches:
  - name: ascii_mode
    reset: 0
    # states: [ 中文, 英文 ]
  - name: full_shape
    # states: [ 半形, 全形 ]
  - name: liu_w2c
    reset: 0
    states: [ 正常 ,反查 ]
  - name: extended_charset
    states: [ 常用, 擴充字集 ]
    reset: 0
  - name: simplification
    states: [ 繁體, 简体 ]
  - name: zh_tw
    reset: 1
```

然後，我在 liur.custom.yaml 裡，設定：
```
  switches/ascii_mode/states: [ 漢字 , 拉丁 ]
  switches/simplification/states: [ 繁, 简 ]
```
這樣一來，選單裡的狀態開關文字確實改變了。

但是我發現，用熱鍵切換（也就是 key_bindings 中用來 toggle 的那些，而不是使用選單）時，彈出的小提示「中/A」、「全角/半角」、「漢字/汉字」，我卻怎麼樣都找不到用來設定的文件。它們似乎是跨方案生效的，不管切換到什麼輸入方案都一樣。然後我到 /Library/Input Methods/Squirrel.app/Contents/SharedSupport 下面研究，也沒有找到哪個文件有設定「中/A」的。

我蠻想自訂這幾個熱鍵開關通知的文字，但不知道是不是被 hard code 了？
