### ISSUE TITLE
enable_completion: false 但還是會有逐碼提示

### ISSUE THREAD

**Issue by GJRobert** [rime/squirrel#369]
我想把輸入方案（是 table 的）的逐碼提示關掉，但已經在 xxxxxxx.custom.yaml 中設為
```yaml
  translator/enable_completion: false
```
了，逐碼提示還是一直跑出來。

有去看 /build 中的 xxxxxxx.schema.yaml，`translator/enable_completion` 確實已經是 `false` 了。

我用的鼠鬚管是 0.14.0

**Comment by GJRobert** [comment]
我用的 schema 是 [rime-liur](https://github.com/hsuanyi-chou/rime-liur/blob/master/Rime/liur.schema.yaml)，後來我發現 /build/liur.schema 裡面有它的 `fixed/enable_completion` 是 `true`，再細看原始碼，第 58 行它宣告了一個 `fixed` translator，然後第 114、115 行 `fixed` 引用了 107 行 `translator/enable_completion` 是 `true`。

所以我在 liur.custom.yaml 中設定：
```yaml
...
  translator/enable_completion: false
  fixed/enable_completion: false
```
兩個都關掉，就解決了。
