### ISSUE TITLE
「default.custom.yaml」deploy 后实际行为与预期不符

### ISSUE THREAD

**Issue by Shinolr** [rime/squirrel#379]
打开了「default.custom.yaml」部分代码的注释，如下：
```
ascii_composer: 
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: noop
```
保存并部署后并未对「build/default.yaml」对应部分造成任何影响：
```
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: inline_ascii
    Shift_R: commit_text
```
实际使用时也没有执行预期行为。
似乎无论如何更改「default.custom.yaml」，只要进行部署，「build/default.yaml」里如 `Shift_L` 字段就会变成 `inline_ascii`。

请问正确的配置方法是什么？
