### ISSUE TITLE
如何取消app_options中的设定

### ISSUE THREAD

**Issue by ArchCST** [rime/squirrel#389]
MacOS， emacs evil-mode。

我现在的情况如下：
1. 在insert-mode中使用rime，按下esc进入normal-mode，此时fcitx-remote自动将输入法切换到英文。
2. 按i再次进入insert-mode，输入法自动通过fcitx-remote切换回rime，理想状态是能直接输入中文，但rime此时在ascii_mode中，无法输入中文，状态是这样：
<img width="264" alt="CleanShot 2019-12-17 at 14 11 46@2x" src="https://user-images.githubusercontent.com/41679407/70969695-67d08e00-20d7-11ea-9abc-742e32724b57.png">

我已经使用了 fcitx-remote 来控制 normal-mode 和 insert-mode 关于 esc 的输入法切换，所以 squirrel.yaml 中的这一段是多余的：
```
org.gnu.Emacs:
    ascii_mode: true
    no_inline: true
```

请问如何 patch 掉这一段？

**Comment by lotem** [comment]
```yaml
# squirrel.custom.yaml

patch:
  app_options/org.gnu.Emacs: {}
```
