### ISSUE TITLE
请教各位大佬鼠须管2个问题，我搞不定了。。。

### ISSUE THREAD

**Issue by man2018** [rime/squirrel#390]
目前我用的是“五笔-拼音”方案，目前无法实现：
1、繁体字输入模式下无法自动造词
2、五笔模式下不知道怎么配置custom_phrase.txt文件到wubi-pinyin.custome.yaml里面起到简体繁体切换功能。
3、如果在wubi86.cn_en.dict.yaml这个词库里面定义了macos xxx 这个词，但发现错了，需要修改成macos Xxx（多了一个大写X），时，部署后还会存在macos xxx这个自定义词

以上3个问题确实不知道该怎么样修改了，请求各位大佬帮帮我，不胜感激

以下是我wubi_pinyin.custom.yaml配置内容：
```yaml
# wubi_pinyin.custom.yaml
# encoding: utf-8

patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: extended_charset
      states: [ 常用, 增廣 ]
    - name: simplification
      reset: 0
      states: ["汉字", "漢字"]
    - name: show_emoji
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
    - name: ascii_punct
      states: [ 。，, ．， ]

  simplifier:
      opencc_config: s2t.json  # 简入繁出

  engine/filters:
    - simplifier
    - uniquifier
    - simplifier@emoji_conversion

  emoji_conversion:
    opencc_config: emoji.json
    option_name: show_emoji
    tags: abc


  # "speller/max_code_length": 4 #最长4码
  "speller/auto_select": true #顶字上屏
  "speller/auto_select_unique_candidate": true #无重码自动上屏
  
  "translator/dictionary": wubi86 #加载五笔词库
  #"translator/dictionary": wubi86.extended #加载五笔扩展词库
  "reverse_lookup/comment_format/@1": xform/^(\w+).*/$1/
  "translator/enable_encoder": true

#  符号快速输入和部分符号的快速上屏
  punctuator:
    import_preset: symbols
    symbols:
      "/fs": [½, ‰, ¼, ⅓, ⅔, ¾, ⅒ ]
      "/bq": [😂️, 😅️, ☺️, 😱️, 😭️, 😇️, 🙃️, 🤔️, 💊️, 💯️, 👍️, 🙈️, 💩️, 😈️ ]
      "/dn": [⌘, ⌥, ⇧, ⌃, ⎋, ⇪, , ⌫, ⌦, ↩︎, ⏎, ↑, ↓, ←, →, ↖, ↘, ⇟, ⇞]
      "/fh": [ ©, ®, ℗, ℠, ™, ℡, ⓘ, ♂, ♀, ☉, ☊, ☋, ☌, ☍, ☐, ☑︎, ☒, ☜, ☝, ☞, ☟, ✎, ✄, ♲, ♻, ⚐, ⚑, ⚠]
      "/xh": [ ＊, ×, ✱, ★, ☆, ✩, ✧, ❋, ❊, ❉, ❈, ❅, ✿, ✲]
    half_shape:
      "#": "#"
      "*": "*"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      "/": ["/", "÷"]
      '\': "、"
      "_" : "──"
      "'": {pair: ["「", "」"]}
      "[": ["【", "["]
      "]": ["】", "]"]
      "$": ["¥", "$", "€", "£", "¢", "¤"]
      "<": ["《", "〈", "«", "<"]
      ">": ["》", "〉", "»", ">"]
  recognizer/patterns/punct: "^/([a-z]+|[0-9]0?)$"

# 加載 easy_en 依賴
  "schema/dependencies/@next": easy_en
  # 載入翻譯英文的碼表翻譯器，取名爲 english
  "engine/translators/@next": table_translator@english
  # english 翻譯器的設定項
  english:
    dictionary: easy_en
    spelling_hints: 9
    enable_completion: true       # 是否启用英文输入联想补全
    enable_sentence: false
    initial_quality: -3           # 调整英文候选词的位置，如 -3 会更靠后     
```

**Comment by KyleBing** [comment]
把代码用 ```yaml  包起来 为好，参考这里：[https://www.runoob.com/markdown/md-code.html](https://www.runoob.com/markdown/md-code.html)

**Comment by man2018** [comment]
@KyleBing 目前显示正常了，但这个issue的问题我还没有找到解决思路，唉，

**Comment by KyleBing** [comment]
打开你要设置的那个方案的 `xxx.schema.yaml` 文件，修改下面对应的字段：

```yaml

switches:
  - name: zh_trad
    reset: 1    # 初始状态为 0: 简 -> 繁 1: 繁 -> 简
    states: [ 简体, 繁体 ]

speller:
#  max_code_length: 4                    # 四码上屏
#  auto_select: true                     # 自动上屏
#  auto_select_unique_candidate: true    # 无重码自动上屏


translator:
  # 开启自动造词相关设置
  enable_sentence: true                # 是否开启自动造词
  enable_user_dict: true               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: true                 # 自动造词
  encode_commit_history: true          # 是否对已上屏的词自动造词
```


<img width="472" alt="Screen Shot 2020-01-09 at 15 52 44" src="https://user-images.githubusercontent.com/12215982/72048978-f7451780-32f8-11ea-8b50-3e0b9ce72e62.png">


> 参考： [https://github.com/KyleBing/rime-wubi86-jidian/blob/master/wubi86_jidian_trad.schema.yaml](https://github.com/KyleBing/rime-wubi86-jidian/blob/master/wubi86_jidian_trad.schema.yaml)
