### ISSUE TITLE
macOS Catalina自带邮件app

### ISSUE THREAD

**Issue by jasonxxu** [rime/squirrel#407]

**Comment by jasonxxu** [comment]
其他软件中使用正常。在mac自带邮件 Mail app中，在邮件编辑界面和查找输入框内均无法通过状态条或者键盘切换到Squirrel输入。

**OS版本：**
macOS Catalina 10.15.3

**Squirrel版本：** （通过brew cask install安装）
squirrel: 0.14.0 (auto_updates)
https://rime.im/
/usr/local/Caskroom/squirrel/0.14.0 (19.6MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/squirrel.rb

**Comment by alex-the-man** [comment]
I cannot reproduce the issue in 10.15.4.

**Comment by weijianwen** [comment]
我在 Big Sur 下能够重现这个问题。在Mail.app的地址栏中无法输入收件人姓名，似乎和Mail的地址检索冲突了。

**Comment by nb5p** [comment]
这样试试呢，可能是占位的空白字符使Mail触发了检测。
```
# squirrel.custom.yaml
patch:
    com.apple.mail:
      inline: true
```
