### ISSUE TITLE
透明背景会留下上一页的残影

### ISSUE THREAD

**Issue by nasyxx** [rime/squirrel#412]
<img width="322" alt="Screen Shot 2020-04-09 at 9 13 59 PM" src="https://user-images.githubusercontent.com/5007613/78953552-3412dd00-7aa7-11ea-88d3-158460c38c6a.png">
<img width="357" alt="Screen Shot 2020-04-09 at 9 14 04 PM" src="https://user-images.githubusercontent.com/5007613/78953558-370dcd80-7aa7-11ea-9619-4b5195fd3925.png">
<img width="358" alt="Screen Shot 2020-04-09 at 9 14 22 PM" src="https://user-images.githubusercontent.com/5007613/78953560-3aa15480-7aa7-11ea-94ba-4e06e73d4037.png">

```yaml
> cat squirrel.custom.yaml
patch:
  preset_color_schemes:
    nasy:
      name: Nasy Color Schemes
      author: Nasy <nasyxx+cc@gmail.com>
      horizontal: true
      inline_preedit: true
      candidate_format: "%c\u2005%@"

      corner_radius: 5
      hilited_corner_radius: 5

      border_height: 5
      border_width: 10
      border_color_width: 0
      font_face: "OperatorMonoSSmLig Nerd Font Book,Kaiti SC"
      font_point: 18
      label_font_point: 18

      back_color: 0x66333333
      border_color: 0xffcafdfe

      text_color: 0xafe9a7
      hilited_text_color: 0xafe9a7
      hilited_back_color: 0x00333333

      hilited_candidate_text_color: 0xafe9a7
      hilited_candidate_back_color: 0x00333333
      hilited_comment_text_color: 0xaf8c6a  # 0x95b5f8

      candidate_text_color: 0xaaffee
      label_color: 0xaaffee
      comment_text_color: 0xafe9a7
  style/color_scheme: nasy

  app_options: {}
```
