### ISSUE TITLE
user.yaml cannot save emoji_suggestion option

### ISSUE THREAD

**Issue by tshu-w** [rime/squirrel#436]
even if I add it manually, this option will be removed after deploy. BTW, I have removed reset in `emoji_suggestion.yaml` and I add this by patch.

```yaml
var:
  last_build_time: 1595226711
  option:
    ascii_punct: false
    full_shape: false
    simplification: true
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1591670882
    luna_pinyin: 1591670855
```
