### ISSUE TITLE
可否添加豎排的候選列表風格？

### ISSUE THREAD

**Issue by edward-martyr** [rime/squirrel#446]
就如蘋果自帶的豎排候選風格。

<img width="354" alt="スクリーンショット 2020-08-03 20 39 21" src="https://user-images.githubusercontent.com/42882301/89183852-73bb8280-d5ca-11ea-89da-7c5b8e2761eb.png">

而不是這樣的「縦中横」

<img width="163" alt="スクリーンショット 2020-08-03 20 48 15" src="https://user-images.githubusercontent.com/42882301/89183982-ab2a2f00-d5ca-11ea-990f-b0ad1a56cc63.png">

**Comment by edward-martyr** [comment]
@LEOYoon-Tsaw 很棒啊。不過圖中的數字是不是旋轉錯誤呢

**Comment by LEOYoon-Tsaw** [comment]
> @LEOYoon-Tsaw 很棒啊。不過圖中的數字是不是旋轉錯誤呢

蘇州碼子

**Comment by edward-martyr** [comment]
原來如此，確實是很有趣的應用場景

**Comment by lotem** [comment]
支持上了

**Comment by Edenharder** [comment]
> 支持上了

能否给一个简单的配置案例呢？最新版的鼠须管，我的如下配置并不生效。
```
patch:
 style/horizontal: false                    
 style/color_scheme: native 
 style/vertical: true
 text_orientation: vertical
```

**Comment by lotem** [comment]
```yaml
patch:
  style/color_scheme: aqua
  style/color_scheme_dark: solarized_rock
  style/candidate_list_layout: stacked # linear #
  style/text_orientation: vertical # horizontal #
  style/base_offset: 6
```
