### ISSUE TITLE
关于成对括号的输入，光标定位到中间的问题

### ISSUE THREAD

**Issue by StayTherapy** [rime/squirrel#456]
各位大佬好。

目前 Squirrel 的各项配置已经稳定投入使用，只是关于输入**成对的括号**时在想有没有更方便的办法。
```yaml
# 通过修改左括号 `[` 的输入值一次输入完整括号对
...
punctuator:
  half_shape:
    # 选择左括号直接输入括号对
    "[": ["「」", "【】", "〔〕", "［］"]
    # 保留右括号备用 
    "]": ["」", "】", "〕", "］"]
...
``` 
这样可以省去左、右括号需要单独从选单选择的时间，只不过输入完成后光标是定位在末尾，**有没有办法这样输入完成后光标定位到括号中间？**

想过用 `key_binder` ，选择输入后`send`一次左方向键，但是 `when` 条件有限，貌似无法判断当前输入的是不是符号，如果是常规文字就不适用。
