### ISSUE TITLE
升级0.15.0，caps_lock无法切换英文大写

### ISSUE THREAD

**Issue by elijewelry** [rime/squirrel#508]
未改动任何文件，直接升级，然后`caps_lock`和原生输入法一样只能切换中英文和长按锁定大写。
```
  ascii_composer/good_old_caps_lock: true     
  ascii_composer/switch_key:
    Caps_Lock: commit_code                 
    Shift_L: noop                      
    Shift_R: noop                           
    Control_L: noop
    Control_R: noop
```
