### ISSUE TITLE
如何利用 iCloud 同步用户数据？

### ISSUE THREAD

**Issue by ililu2000** [rime/squirrel#509]
如何利用 iCloud 同步用户数据？需要如何设置

**Comment by StayTherapy** [comment]
按我目前的理解，Squirrel 的**同步**跟一般理解的同步不太一样，其作用更偏向于**备份**，也就是当前生效的配置会**复制**到指定的目录，这个复制是单向的，换句话说备份目录的修改并不会**反向作用**于当前生效的配置；另外跨设备之间配置也不会合并（所有设备的同步目录均指向 iCloud，则每个设备会有一个同步目录 ），好像只有用户输入词典（跟自定义词典还不一样，是自动生成的 schema.userdb.txt）会合并，但是这个我没仔细验证过。

不知道你的需求是不是这样的？

具体配置的话，在用户设定的 `installation.yaml` 文件中配置：

```yaml
# 可选，指定设备 ID，即同步目录的名称，不指定则为自动生成的随机ID
installation_id: DEVICE
# 指定到 iCloud 某个目录
sync_dir: "/path/to/icloud"
```
