### ISSUE TITLE
[文件] 能否給出完整的 style 設定項目清單，以及預設值？

### ISSUE THREAD

**Issue by GJRobert** [rime/squirrel#528]
這是我的 0.14 的外觀：
![screenshot](https://user-images.githubusercontent.com/655584/107840200-c08adc00-6deb-11eb-9494-235a57977c46.png)

更新到 0.15 後，尚未調整任何設定，panel 就變這樣：
![2021-02-13_09-17-05](https://user-images.githubusercontent.com/655584/107840219-e7e1a900-6deb-11eb-991a-e2d55e9d2a1e.png)

- `line_spacing` 經過重新調整後已經恢復正常
- 但是 panel 的左右邊界似乎變得更寬了（which 我不太喜歡）。我把 `border_width` 調成 `0` 了，但還是一樣多出我覺得太寬的邊邊。是這次更新中推出了其他的 padding 設定嗎？
- 感覺 0.14 的 panel，不管行內使用什麼字型（我把漢字和字母數字設為不同的字型，在 `font_face` 裡使用數個字型 fallback），每行的行高都是一致的（這樣比較整齊）；到了 0.15，就會因為該行出現的字型不同，而有不同的行高，而且漢字的的 baseline 也變得偏下了，導致 panel 看起來比較零亂。是因為有新的參數 `base_offset` 要設定嗎？

因為從 0.14 → 0.15，panel style 設定項目的變動比較大，如果可以透過調整設定讓 panel 維持跟之前一樣的外觀，是無所謂；但目前因為社群中缺乏完整的設定項目清單及預設值，以及可能是改版過程中修改了某些 behavior，所以導致我重新調校的過程比較吃力。社群 wiki 文件雖然尚未更新，但問題不大，我想，若能有完整的 official list，至少我可以嘗試一些還沒有使用到的設定項目去找出問題所在。

**Comment by LEOYoon-Tsaw** [comment]
不同字體行高不一樣是有可能的，Emoji專門處理過，但不可能針對每個字體去處理。可以把行距調高一些就不太看得出來了，如果還是在意，就不要升級0.15版。
四圍的最小邊距稍有變大，同樣，如果非常在意，就不要升級0.15版。
只新引入了base_offset一個參數

**Comment by lotem** [comment]
​請​給出​​與​圖示​對應的​完整​設定​代碼。​只看圖​看不明白​​顏色​爲什麼會​改變，​​也​沒法​分析下面​提到的​具體​​​問題。

​​完整設定​項目​清單，​包含​註釋掉的​代碼：
https://github.com/rime/squirrel/blob/master/data/squirrel.yaml#L14

**Comment by GJRobert** [comment]
抱歉，顏色的部分是因為用了不同的 color scheme。那個部分不管的話，我原本在 0.14 使用的設定碼如下：
```
  style/inline_preedit: false
  style/font_face: Operator Mono Bold, Latinghei TC Bold, Latinghei SC Bold

  style/font_point: 18 #20          # 字號
  style/corner_radius: 5       # 窗口圓角半徑
  style/border_height: 7        # 窗口邊界高度，大於圓角半徑才有效果
  style/border_width: 0         # 窗口邊界寬度，大於圓角半徑才有效果
  style/line_spacing: 5
  style/spacing: 2
  style/label_font_face: DFLiKingHei-XB #Operator Mono Bold Italic #編號的字型
  style/label_font_point: 12
  style/hilited_corner_radius: 5 #高亮度區的圓角
  style/candidate_format: "%c%@"
```

**Comment by lotem** [comment]
​研究了一下代碼，多出來的部分應該是這裏註釋提到的5px邊距：
https://github.com/rime/squirrel/blob/e8b87a4f97994001c6889ecc1d43fa38e7589e66/SquirrelPanel.m#L233

**Comment by lotem** [comment]
由於​採用新的文字排版技術的改動不以100%還原舊版本的樣式爲目標，這個問題不應視爲BUG。
就樓主的定製外觀而言，有幾處文字的排版過於緊湊，適當增加一些空白也未嘗不可。

**Comment by GJRobert** [comment]
我的 0.14 擷圖（紅豆色那張圖）可以看出，行距應該不至於緊湊。同樣的設定直接升級到 0.15（灰綠色那張圖）以後，一開始就變成 0 行距，但我把 `line_spacing` 改動後重新存檔，再重新部署後，就比較正常，所以我也不清楚為什麼剛升級時會不正常～

`5px empty edge on both sides` 這個我可以接受，我就相應增加上下 `border_height`，並把 `border_width` 改為 `0` 了（因為等於原本已預留 5px）

我同意這題並不是以提交 bug 為目的，原本只是想瞭解有沒有我 miss 掉的參數（感謝 @lotem 老大提供）。文字垂直對齊的部分，目前我把 `base_offset` 設為 `-3`，並加大了 `line_spacing = 5`，來緩解不同字型造成的不同行高：
![2021-02-14_11-37-15](https://user-images.githubusercontent.com/655584/108145886-25557780-7107-11eb-881d-0d617bb6c19f.png)
不過不同字型造成的不同行高還是可以稍微感覺得出來，例如上圖中，第 2、3、4、5 項的行高看來是一樣的，但第 1、6 項，可能因為 fallback 到系統的某個其他字型（不是我設定的蘭亭黑），行高就變得較大。不過，如果說因為 0.15 使用不同排版技術導致這個差異，那我就先與它相處。

以下是我修改後目前使用的 squirrel style：
```yaml
  style/font_face: Operator Mono Bold, Latinghei TC Bold, Latinghei SC Bold
  style/font_point: 18 #20          # 字號
  style/corner_radius: 5       # 窗口圓角半徑
  style/border_height: 7        # 窗口邊界高度，大於圓角半徑才有效果
  style/border_width: 0         # 窗口邊界寬度，大於圓角半徑才有效果
  style/line_spacing: 5
  style/spacing: 2
  style/label_font_face: DFLiKingHei-XB #Operator Mono Bold Italic #編號的字型
  style/label_font_point: 12
  style/hilited_corner_radius: 5 #高亮度區的圓角
  style/candidate_format: "%c%@"
  style/base_offset: -3
```
