### ISSUE TITLE
希望增加"开启 Emoji 表情" 和 "关闭 Emoji 表情" 切换的状态指示。

### ISSUE THREAD

**Issue by ililu2000** [rime/squirrel#535]
<img width="75" alt="1" src="https://user-images.githubusercontent.com/78154435/107899564-9404ca80-6f79-11eb-9ba7-1a505987487a.png">

如图，中英文、全半角、简繁体、字符集的状态切换都有状态指示。唯独开启和关闭 Emoji 表情没有。

**Comment by LEOYoon-Tsaw** [comment]
這個我可以考慮有空做一下

**Comment by moriwang** [comment]
这个状态指示有办法自己定义里面的内容吗？目前看源码是用语言包写死的。

使用场景就是我使用 OpenCC 做了一些自定义词库，使用快捷键做切换，有提示会比较清楚是否切换成功。
因为已经在 switches 的 states 里定义了内文，想请问直接显示于状态指示是否可行呢？

**Comment by LEOYoon-Tsaw** [comment]
想辦法把`states`直接傳出來就行了

**Comment by LEOYoon-Tsaw** [comment]
試試看吧

**Comment by Eason0210** [comment]
@ililu2000  我使用的下面这个朙月拼音和小鹤双拼的方案，可以实现关闭表情。你可以参考下面这个配置。
[rime-settings](https://github.com/wongdean/rime-settings/blob/master/luna_pinyin.custom.yaml)

在相应方案的custom文件中（比如luna_pinyin.custom.yaml）加入一下代码：
```
switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: emoji_suggestion
      reset: 1
      states: [ "Yes", "No" ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      reset: 1
      states: [ 漢字, 汉字 ]
    - name: ascii_punct
      states: [ 。，, ．， ]
```

![image](https://user-images.githubusercontent.com/47546452/115944742-36957880-a4ea-11eb-822b-9323bb95dec6.png)
