### ISSUE TITLE
Squirrel cannot load emoji_suggestion state from user.yaml

### ISSUE THREAD

**Issue by tshu-w** [rime/squirrel#545]
I change emoji_suggestion from on to off and see the option successfully saved in `user.yaml` by IME, however, when I deploy Squirrel again, the emoji_suggestion is still on.  simplification and other options can be loaded correctly. Am I missing something?

user.yaml:
```yaml
var:
  last_build_time: 1614738912
  option:
    emoji_suggestion: false
    simplification: true
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1614736644
    luna_pinyin: 1614736633
```

default.custom.yaml:
```yaml
patch:
  schema_list:
    - schema: double_pinyin_flypy  # 小鹤雙拼
    - schema: luna_pinyin          # 朙月拼音

  switcher/save_options/+:
    - emoji_suggestion
```

emoji_suggestion.yaml:
```yaml
# encoding: utf-8

patch:
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    # tips: all
```

Squirrel 0.15.2
macOS 11.2.2
