### ISSUE TITLE
请问 switches 可以联动吗？

### ISSUE THREAD

**Issue by nasyxx** [rime/squirrel#553]
是这样的，我有两个 switches 希望联立在一起使用。这两个都是 opencc 用在 simplifier 处的

```yaml
switches:
  - name: s1
    ...
  - name: s2
    ...

filters:
  - simplifier@s1
  - simplifier@s2
```

大概就是 
- s1 在 state 1 的时候，s2 处在 state 1
- s1 在 state 2 的时候，s2 也处在 state 2

目前我是用两个快捷键分别改变这两个状态，但还是感到有点麻烦。
