### ISSUE TITLE
engine设置中,单个选项设置无法用冒号+缩进表示

### ISSUE THREAD

**Issue by happypandaa** [rime/squirrel#557]
失败:

```
	engine:
  	  processors:
    	    - key_binder
	translator:
```

成功:
```
    engine:
      processors:
    	    - key_binder
      segmentors:
	    - ascii_segmentor
    translator:
```
成功:
```
    engine/processors:
      - key_binder
     translator:
```

大概意思就是，如果某项的子项目只有一个集合{bbbb:cccc}，那么就必须写成 aaaa/bbbb: ccc。
