### ISSUE TITLE
若將 switches reset 設為 1 時，在通知欄無法輸入

### ISSUE THREAD

**Issue by tsaiid** [rime/squirrel#56]
Mac: 10.10.4
Squirrel: 0.9.26.2

若將 schema.yaml 中設定如下（希望預設是英數模式）

```yaml
switches:
  - name: ascii_mode
    reset: 1
```

在通知欄（如圖 twitter 輸入框）會出現無法輸入的狀況，試了 luna_pinyin, bopomofo，除了 `reset` 更改為 1 之外，其餘設定皆為預設，應與輸入法無關。

<img width="355" alt="2015-07-06 00 09 49" src="https://cloud.githubusercontent.com/assets/4302689/8512429/ed47b1ea-2374-11e5-8b88-eee5ab52f601.png">
