### ISSUE TITLE
0.15.2 只自定义部分字符不起作用

### ISSUE THREAD

**Issue by dwSun** [rime/squirrel#572]
luna_pinyin_simp.custom.yaml
中添加了如下配置
```yaml
patch:
  punctuator/full_shape:
    - "#":  "#"
    - "@":  "@"
  punctuator/half_shape:
    - "#":  "#"
    - "@":  "@"
```

部署之后,#@是可以直接上屏了,但是其他的所有字符都无法输入了.

差查了一下配置文件,build 下面的 luna_pinyin_simp.schema.yaml punctuator 字段,整个都被替换掉了.

我只是想对上述两个字符进行定制,其他的想要保持不变,请问应该如何写这个配置文件.已经试过了下属方式也不起作用,跟上面的配置一样的效果:

```yaml
patch:
  punctuator:
    import_preset: symbols
    full_shape:
      - "#":  "#"
      - "@":  "@"
    half_shape:
      - "#":  "#"
      - "@":  "@"
```
