### ISSUE TITLE
mac下聚焦搜索和终端无法输入中文简单解决方案

### ISSUE THREAD

**Issue by nulllpoint** [rime/squirrel#584]
- 从highserria时候起就发现mac下 聚焦搜索和终端界面用鼠须管(14.x)输入时无法输入中文, 
最近用mbp bigsur系统和最新版本的鼠须管15.x+ 发现还是一样的问题.
- 于是折腾了一番, 最终发现了, 用户设定下default.custom.yaml文件里有'ascii_composer/switch_key: ', 开始事直接将此配置下所有内容注释, 发现shift可以在鼠须管下切换中英模式, 这里的英文模式不是macos的内置英文输入. 
进而推测在聚焦搜索和终端时, 不知道什么原因鼠须管会优先使用自己的英文模式, 又因为默认配置的shift和caps_lock都是noop, 即无法切换成鼠须管的中文输入模式.
- 按找此思路, 最终将caps_lock依然配置成系统的中英切换, ctrl或shift设置成鼠须管的中英切换, 算是目前通过调整配置能达到的最完美的体验, 诚挚的希望官方能优化下.
- 附最终配置代码: 
  ```yml
    ascii_composer/switch_key:
      Caps_Lock: noop
      # Shift_L: commit_code
      Shift_L: noop
      # Shift_R: noop
      Control_L: commit_code
      # Control_L: noop
      # Control_R: noop
  ```
- 效果: 
  
<img width="731" alt="WechatIMG25" src="https://user-images.githubusercontent.com/42410451/130739013-ebcc240c-51b1-4dad-a28f-3f208d25593b.png">

### 最后感谢rime这么好的全平台输入法, 很理解开源且免费项目的不易, 不胜感激!
