### ISSUE TITLE
vim_mode doesn't works for emacs

### ISSUE THREAD

**Issue by linchen2chris** [rime/squirrel#625]
I add 
```
patch:
  app_options:
    com.jetbrains.intellij:
      ascii_mode: true
      vim_mode: true
    org.gnu.Emacs:
      ascii_mode: true
      vim_mode: true
``` 
in squirrel.custom.yaml, vim_mode works for intellij, but not works for emacs.
