### ISSUE TITLE
Safari 输入框不停地被切换到中文

### ISSUE THREAD

**Issue by kkew3** [rime/squirrel#627]
`macOS Monterey Version 12.3.1`, `Safari Version 15.4 (17613.1.17.1.13)`.

使用问题案例：

1. 打开Safari，在应用顶部的搜索框中键入，发现是中文，按Shift切换成英文，之后不再切换回中文。
2. 焦点移至百度搜索引擎的搜索框，发现被自动切换到中文，按Shift切换成英文，然后一直输入英文。
3. 关掉百度搜索引擎，然后重新打开百度，焦点移至百度搜索框，发现被自动切换到中文，按Shift切换成英文。
4. 按Commanf-F搜索，输入，发现又被自动切换到中文，按Shift切换成英文。
5. 随便打开一个带文本框的网站，比如https://www.tablesgenerator.com ，在表格中输入文字，发现又被自动切换到中文，再次按Shift切换成英文...

希望能一直呆在鼠须管这一个输入法下，而不是时不时切换到macOS的U.S.键盘下。

贴上我的配置：

`default.custom.yaml`:

```yaml
patch:
  menu/page_size: 5
```

`squirrel.custom.yaml`:

```yaml
patch:
  style:
    horizontal: true
  app_options/com.runningwithcrayons.Alfred:
    ascii_mode: true
  app_options/com.microsoft.VSCode:
    ascii_mode: true
```

非常感谢！
