### ISSUE TITLE
重複輸入 bracket left 或 bracket right 時行為不符合預期

### ISSUE THREAD

**Issue by chivincent** [rime/squirrel#635]
因自定義輸入法字典中存在以下內容

```
『	[[
』	]]
```

但在 macOS 12.3 時使用鼠鬚管如果按下兩次 `[` 鍵則會移動至次一候選字，而非預期的輸入兩次 `[`：
![截圖 2022-05-06 上午9 06 40](https://user-images.githubusercontent.com/7449005/167050480-3c254222-5dd2-4fac-90bb-9bb4576428e3.png)

不確定是不是設定上有些問題，以下是設定檔

```yaml
schema:
  schema_id: boshiamy
  name: 嘸蝦米
  version: "0.1"
  author: 
    - 劉重次
  description:
    嘸蝦米輸入法 For RIME

switches:
  - name: ascii_modea
    reset: 0
    states: [ 漢字, 英數 ]
  - name: full_shape
    states: [ 半形, 全形 ]
  - name: simplification
    states: [ 繁體, 打繁出簡 ]
  - name: ascii_punct
    reset: 0
    states: ["標點", "符號"]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - punctuator
    - speller
    - selector
    - navigator
    - express_editor
  segmentors:
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - echo_translator
    - punct_translator
    - table_translator
  filters:
    - simplifier
    - uniquifier

menu:
  page_size: 10
  alternative_select_keys: "0123456789"


speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz,.'[]"
  max_code_length: 5
  auto_select: false

translator:
  dictionary: boshiamy
  enable_charset_filter: true # 可以把 EXT 區的漢字給過濾掉
  enable_completion: false # 不提示後續按鍵的組字結果
  enable_sentence: false # 關閉連打組句。若要啟動的話需要打開 speller/delimiter 及 enable_user_dict
  enable_user_dict: false # 取消使用者字頻調整機制。若打開的話則無法維持候選字順序。
  preedit_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz,.'[]|ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ，．’〔〕"

key_binder:
  bindings:
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+Shift+4, toggle: simplification }
    - { when: has_menu, accept: space, send: space }
    - { when: has_menu, accept: period, send: period }
    - { when: composing, accept: space, send: Escape }

punctuator:
  import_preset: default

recognizer:
  import_preset: default
```
