### ISSUE TITLE
简化字方案的简繁切换提示问题

### ISSUE THREAD

**Issue by iDvel** [rime/squirrel#636]
如图，朙月拼音使用快捷键切换简繁后会出现这个提示：
<img width="165" alt="image" src="https://user-images.githubusercontent.com/14658234/167576540-2e90826c-8f35-48bb-8a7a-05b356eb3089.png">

但我用的是袖珍简化字方案，我是这么设置简繁切换的：
```yaml
switches:
  - name: traditionalization
    reset: 0
    states: [ 简, 繁繁繁 ]
# ...
engine:
  filters:
    - simplifier@traditionalize
# ...
traditionalize:
  opencc_config: s2t.json
  option_name: traditionalization
```

我切换简繁时不会有任何提示。
除非我把 `option_name: traditionalization` 改成 `option_name: simplification`，但这样我从默认简体切换到繁体，提示的是「汉字」，切回简体提示的是「漢字」，反了。

---

<img width="540" alt="image" src="https://user-images.githubusercontent.com/14658234/167577018-1373d259-cf90-4208-a81e-a02049262e60.png">

我不太懂，是不是这里增加以下两行就可以适用简化字方案了呀：
```
"simplification" = "汉字";
"!simplification" = "漢字";
"traditionalization" = "漢字";
"!traditionalization" = "汉字";

             !strcmp(message_value, "simplification") ||
             !strcmp(message_value, "!simplification") ||
             !strcmp(message_value, "traditionalization") ||
             !strcmp(message_value, "!traditionalization") ||
```
