### ISSUE TITLE
候选框接触到屏幕边缘后, 长度不再随候选词动态变化

### ISSUE THREAD

**Issue by sirlaurie** [rime/squirrel#639]
Hi, 我用的是0.15.2版本的Squirrel, 使用的皮肤配置如下

  ```yaml
  patch:

    show_notifications_when: appropriate                              # 状态通知，适当，也可设为全开（always）全关（never）

    style:
      color_scheme: apathy

    preset_color_schemes:

      apathy:

        name: "冷漠 / Apathy"
        author: "LIANG Hai "

        horizontal: true                                               # 水平排列
        inline_preedit: true                                           # 单行显示，false双行显示
        candidate_format: "%c\u2005%@\u2005"                           # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
        corner_radius: 5                                               # 候选条圆角
        border_height: 0                                               # 窗口边界高度，大于圆角半径才生效
        border_width: 0                                                # 窗口边界宽度，大于圆角半径才生效
        back_color: 0x202020                                           # 候选条背景色
        border_color: 0xFFFFFF                                         # 边框色
        font_face: "PingFangSC-Regular,HanaMinA"                       # 候选词字体
        font_point: 16                                                 # 候选字词大小
        text_color: 0x424242                                           # 高亮选中词颜色
        label_font_face: "PingFangSC-Regular"                          # 候选词编号字体
        label_font_point: 13                                           # 候选编号大小
        label_color: 0xcbcbcb                                          # 预选栏编号颜色
        candidate_text_color: 0xB0B0B0                                 # 预选项文字颜色
        text_color: 0xFFFFFF                                           # 拼音行文字颜色，24位色值，16进制，BGR顺序
        comment_text_color: 0x999999                                   # 拼音等提示文字颜色
        hilited_text_color: 0xFF6941                                   # 高亮拼音 (需要开启内嵌编码)
        hilited_candidate_text_color: 0xFFFFFF                         # 第一候选项文字颜色
        hilited_candidate_back_color: 0xFF6941                         # 第一候选项背景背景色
        hilited_candidate_label_color: 0xFFFFFF                        # 第一候选项编号颜色
        hilited_comment_text_color: 0xFF6941                           # 注解文字高亮
  ```

在最近的几个macOS大版本中, 我一直都有遇到这样的问题:

当按下按键, 因为候选词太长, 导致候选框的长度正好接触到屏幕边缘的时候, 这个候选框就不会再自动收回来了, 即使候选词的长度都变短了.  如果在候选词变化的过程中, 候选框没有接触过屏幕边缘, 那么他的长度就一直随着候选词动态变化. 

详细可见下面的视频. 视频右边缘是顶到屏幕边缘的

https://user-images.githubusercontent.com/8928155/169696806-c1a8585c-bab8-4cf0-8b2b-ed7052dbc021.mov
