### ISSUE TITLE
是否可以限制鼠须管使用固定的键盘布局？

### ISSUE THREAD

**Issue by twio142** [rime/squirrel#649]
当从法语、德语键盘切换到鼠须管时，会保留之前的 keyboard layout。系统的中文输入法有一个选项可以始终使用基础的英文键盘布局。鼠须管有办法做到吗？

**Comment by lotem** [comment]
可以的。

**Comment by twio142** [comment]
@lotem 请问需要怎么做呢？

**Comment by lotem** [comment]
修改这项配置为`true`，使用美式键盘布局。

https://github.com/rime/squirrel/blob/f4d721010e8dbcc954eda08ddaf836d931ca2549/data/squirrel.yaml#L6

**Comment by easonwong-de** [comment]
For anyone else’s interest, to force US keyboard layout, edit `squirrel.custom.yaml` to:

```yml
patch:
    ...
    keyboard_layout: USExtended
    ...
```
