### ISSUE TITLE
自定义字体大小导致输入候选框出现 emoji 时会向下偏移浮动

### ISSUE THREAD

**Issue by lvii** [rime/squirrel#660]
Hi

macOS Monterey 下安装的最新 `0.15.2` 版本：

- 修改输入候选框 **字体大小**
- 当输入框同时 **中文 + Emoji** 文字时，输入框整体会出现向下偏移现象

![CleanShot 2022-08-27 at 01 13 19@2x png](https://user-images.githubusercontent.com/309721/186958181-adf6f9f7-5c88-474d-acfc-88ee6f5d8d8f.png)

修改 [自带 `purity_of_essence` 主题](https://github.com/rime/squirrel/blob/master/data/squirrel.yaml) 的 **字体大小** 问题复现：

``` yaml
  # 选择皮肤：
  style/color_scheme: purity_of_essence_custum
  style/candidate_list_layout: linear

    purity_of_essence_custum:
      name: 純粹的本質／Purity of Essence
      author: 佛振
      text_color: 0x2c2ccc
      back_color: 0xfafafa
      candidate_text_color: 0x000000
      hilited_text_color: 0x000000
      hilited_back_color: 0xfafafa
      hilited_candidate_text_color: 0xeeeeee
      hilited_candidate_back_color: 0x444444
      comment_text_color: 0x808080
      corner_radius: 5                              # 窗口圆角
      font_face: "PingFangSC"                       # 候选字体
      label_font_point: 16                          # 编号大小
      # font_point: 18                              # 中文大小  <-- 启用该设置，问题复现
```

**Comment by oniondelta** [comment]
這邊有方案選字單，含中文、拉丁字母、日語、韓語、Emoji 等，
因各種語言匹配字體不同（不同字體，字號大小一樣，高度不一定一樣）
發生所佔高度大小不一，邊打邊跳動情形。

### 目前解法是：
設定（前標號：1. 2. 3.）「前標號字體」和「前標號字號大小」，
因為前標號一定會在選單中，使其高度一直很大，
甚可再微調「一般字體」和「一般字號」
如設定不佳，視覺上會偏醜，自行設定斟酌。

squirrel.custom.yaml 中
```
patch:
  style/label_font_face: 'NotoSansMono-Regular' # 前標號字體
  style/label_font_point: '22' # 前標號字號大小
  style/font_face:'NotoSerif-Regular,NotoSansCJKtc-Light,AppleColorEmoji,HanaMinA,HanaMinB' # 一般字體
  style/font_point: '17' # 一 般字號

```
