### ISSUE TITLE
iTerm 中 vim_mode 无法响应 <C-c> 及 <C-[>

### ISSUE THREAD

**Issue by Deeperand** [rime/squirrel#668]
我发现在其它软件中设置 `vim_mode: true` 后除了 `<ESC>` 外, `<C-c>` 及 `<C-[>` 被按下时也可切换为英文模式, 但 iTerm.app 中只有 `<ESC>` 可响应。此外 Terminal 中 `<ESC>`, `<C-c>`, `<C-[>` 在按下时均无法切换为英文模式。目前怀疑这两个软件内部可能存在潜在的与 `<C-c>` `<C-[>` 等按键的快捷键冲突。

下面是我的 Squirrel 配置, 如前所述, 除了 iTerm 及 Terminal 外, 诸如 MacVim, VSCode, Obsidian 等软件中均可通过按下 `<C-c>` 及 `<C-[>` 来实现切换为英文模式
```
    app_options:
      com.microsoft.VSCode:
        ascii_mode: true
        vim_mode: true
      org.vim.MacVim: # you should find
        ascii_mode: true
        # allowed switch to English input when <ESC> pressed, and don't need double press <ESC> in macvim anymore
        vim_mode: true
        #no_inline: false
      com.apple.Terminal:
        ascii_mode: true
        vim_mode: true
        #no_inline: false
      com.googlecode.iterm2:
        ascii_mode: true
        vim_mode: true
      md.obsidian:
        vim_mode: true
        ascii_mode: true
```

**Comment by Nauxscript** [comment]
测试了一下发现 iTerm2 已经可以使用了；

- MacOS：Ventur 13.1
- iTerm2：3.4.19

配置：
```yaml
com.googlecode.iterm2:           # iterm2
      ascii_mode: true
      vim_mode: true
``` 

注：我是全局把 `ctrl` + `[` 映射为 `Esc` 的。

但 `Terminal` 还是不行。
