### ISSUE TITLE
bopomofo.custom.yaml部署後未獲納入

### ISSUE THREAD

**Issue by mgeorgetw** [rime/squirrel#691]
這是系統更新至macOS Ventura後才發現的問題，先前的部署都有效果。

我在用戶資料夾有簡單的`bopomofo.custom.yaml`配置如下：

```yaml
patch:
  # 繪文字輸入方案
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️\uFE0E", "🈶\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: none

  # 標點符號自定義
  punctuator:
    import_preset: bopomofo
    full_shape:
      # 略……

  # 以 Caps Lock 切換到西文模式，默認輸出小寫字母
  ascii_composer/good_old_caps_lock: false

  # Shift和Caps Lock都可以切換中英文
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: commit_code
```

部署後在`build`資料夾中不見任何與bopomofo相關的檔案，但包含類似設定的`luna_pinyin_tw.custom.yaml`依然能成功部署。
