### ISSUE TITLE
0.16.1 按shift键时不再提示中英状态

### ISSUE THREAD

**Issue by Cnly** [rime/squirrel#707]
升级到0.16.1后，按shift键切换中英输入时似乎不会再提示当前的中/英状态。升级之前按shift的时候会在光标处弹小窗提示的。不知道这是不是预期的改动？

系统是 macOS 13.2。

**Comment by LEOYoon-Tsaw** [comment]
沒有遇到這種情況。檢查一下方案中中英文開關是否寫了 states 名，如：
```yaml
  - name: ascii_mode
    reset: 0
    states: ["中文", "西文"]
```

**Comment by Cnly** [comment]
似乎确实是这样，也许原来的版本即使没有添加配置项也会自动显示？我在我的 `.custom.yaml` 的 `patch` 里添加了

```yaml
  'switches/@before 0':
    name: ascii_mode
    reset: 0
    states: [ ' 中 ', ' 英 ' ]
```

后，问题解决了，感谢。
