### ISSUE TITLE
back_color 与 hilited_back_color、hilited_candidate_back_color 背景色不一致

### ISSUE THREAD

**Issue by halfmoonvic** [rime/squirrel#712]
![image](https://user-images.githubusercontent.com/8521726/216293542-b09154dc-139a-41ec-a6f4-c11c05060a5e.png)

这是我的代码
```
light_translucency:
  name: "light_translucency"

  border_width: 0
  border_height: 0
  corner_radius: 6
  hilited_corner_radius: 6
  candidate_format: "%c.\u2005%@\u2005" # %c 指编号 %@ 指候选词

  translucency: true

  back_color: 0x1affffff
  border_color: 0x1affffff

  text_color: 0x333333
  hilited_text_color: 0x000000
  hilited_back_color: 0x1affffff

  candidate_text_color: 0x000000
  hilited_candidate_text_color: 0xbb8423
  hilited_candidate_back_color: 0x1affffff

  label_color: 0x333333
  hilited_candidate_label_color: 0xbb8423
  comment_text_color: 0x333333
```

如图，在代码中，三者颜色设置是一样的，可界面上有一个 active 效果。可以去除这种 active 效果么？

**Comment by lotem** [comment]
有透明度的颜色，文字背景会叠加到视窗背景上。

**Comment by halfmoonvic** [comment]
> 有透明度的颜色，文字背景会叠加到视窗背景上。

我是刚更新的 squirrel。就是在设置透明背景色这一UI。图片中的背景色是一致的。因为 back_color 与 hilited_back_color、hilited_candidate_back_color 是一致的，背景色也是一整块的纯色，所以叠加后的效果按理说也是一致的？

**Comment by halfmoonvic** [comment]
我明白了，是不是 hilited_candidate_back_color 这个颜色的形成是两次叠加的效果。  
即其先叠加到 back_color，而后又叠加到我的物理背景，最终形成了我所见的颜色。  
而 back_color 的效果则是仅叠加了一次物理背景就形成了我所见的效果。  
一个是叠加了两次，另一个仅叠加了一次？

**Comment by halfmoonvic** [comment]
![image](https://user-images.githubusercontent.com/8521726/216300791-9649c612-9a99-4f9a-8f43-0805d47393a6.png)
此图即为我想要的效果，代码如下。
```
light_translucency:
  name: "light_translucency"

  border_width: 6
  border_height: 6
  corner_radius: 6
  hilited_corner_radius: 6
  candidate_format: "%c.\u2005%@\u2005" # %c 指编号 %@ 指候选词

  translucency: true

  back_color: 0x1affffff
  border_color: 0x00ffffff

  text_color: 0x333333
  hilited_text_color: 0x000000
  hilited_back_color: 0x00ffffff

  candidate_text_color: 0x000000
  # hilited_candidate_text_color: 0x9e680f
  hilited_candidate_text_color: 0xc27900
  hilited_candidate_back_color: 0x00ffffff

  label_color: 0x333333
  # hilited_candidate_label_color: 0x9e680f
  hilited_candidate_label_color: 0xc27900
  comment_text_color: 0x333333
```
