### ISSUE TITLE
升级至0.16.1后tab键操作由移动拼音光标变为了向右移动选中候选词

### ISSUE THREAD

**Issue by wx40217** [rime/squirrel#716]
升级前tab可以在输入多个拼音时移动到第一个拼音的结尾 再按一下就往右移一个拼音 
升级后tab就变成移动当前选中的候选词了
检查build里的default.yaml tab绑定的设置仍是Shift+Right
<img width="656" alt="image" src="https://user-images.githubusercontent.com/24869295/216533441-a24ef775-f607-47e7-98f2-48127426037c.png">

**Comment by widcardw** [comment]
我也遇到这个问题了，修改 `default.custom.yaml` 之后，快捷键配置是这样的，但是原本的按键映射现在不是那么适配了。

```yaml
patch:
  key_binder/bindings:
    - { when: composing, accept: Control+p, send: Up }
    - { when: composing, accept: Control+n, send: Down }
    - { when: composing, accept: Control+b, send: Left }
    - { when: composing, accept: Control+f, send: Right }
    - { when: composing, accept: Control+a, send: Home } # 光标跳转至行首
    - { when: composing, accept: Control+e, send: End }  # 光标跳转至行尾
    - { when: composing, accept: Control+d, send: Delete }
    - { when: composing, accept: Control+k, send: Shift+Delete }

    - { when: composing, accept: ISO_Left_Tab, send: Shift+Left }
    - { when: composing, accept: Shift+Tab, send: Shift+Left }
    - { when: composing, accept: Tab, send: Shift+Right }
```

https://user-images.githubusercontent.com/55699713/216751677-cc0ceed7-3593-4ade-ae0c-751697e5b6ca.mp4

**Comment by widcardw** [comment]
这个问题在配置了 `squirrel.custon.yaml` 为下面的情况，即候选词横向排列时出现，如果是纵向排列，那么就不会出现这样的问题

```yaml
patch:
  style:
    # 横向排列
    candidate_list_layout: linear
    text_orientation: horizontal
```

https://user-images.githubusercontent.com/55699713/216752681-73c52b6a-846f-4e0c-9001-675407dfa5ac.mp4
