### ISSUE TITLE
无法覆盖默认快捷键

### ISSUE THREAD

**Issue by RoyRao2333** [rime/squirrel#718]
以下是我的快捷键绑定：

<img width="762" alt="image" src="https://user-images.githubusercontent.com/31413093/216569440-efbbda81-19e1-45cb-b7ff-862e8ab6ebdf.png">

如图所示，原先`default.custom.yaml`的`Ctrl + Shift + 4`是**简繁切换**，现在我的`Ctrl + Shift + 4`已经改为**显示生僻字**，但是当我按出快捷键后，依然会显示简繁切换的标识，也就是说我的改动似乎没有生效。（改过的1、2、3快捷键都正常，只有4没有生效）

**Comment by lotem** [comment]
請給出配置代碼以便分析。

**Comment by RoyRao2333** [comment]
> 請給出配置代碼以便分析。

`default.custom.yaml`:

```yaml
patch:
  schema_list:
    - schema: luna_pinyin_simp # 朙月拼音
    - schema: double_pinyin_flypy # 小鹤双拼
    - schema: double_pinyin # 自然码双拼
    - schema: numbers # 大写数字

  menu/page_size: 9 # 候选词个数

  ascii_composer/good_old_caps_lock: true # 若为 true， Caps 只切换大小写
  
  ascii_composer/switch_key:
    Caps_Lock: commit_code # Caps 键
    Shift_L: commit_code # 左 Shift，切换中英文
    Shift_R: commit_code # 右 Shift，切换中英文
    Control_L: noop # 左 Control，屏蔽该切换键
    Control_R: noop # 右 Control，屏蔽该切换键

  key_binder/bindings:
    # 翻页
    - { when: composing, accept: Tab, send: Shift+Right } # "tab" 键分词
    - { when: paging, accept: minus, send: Page_Up } # "-" 上一页
    - { when: has_menu, accept: equal, send: Page_Down } # "=" 下一页
    - { when: paging, accept: comma, send: Page_Up } # "," 上一页
    - { when: has_menu, accept: period, send: Page_Down } # "." 下一页
    - { when: paging, accept: bracketleft, send: Page_Up } # "[" 上一页
    - { when: has_menu, accept: bracketright, send: Page_Down } # "]" 下一页
    # 快捷键
    - { when: always, accept: Control+Shift+1, toggle: zh_simp } # 繁简体切换
    - { when: always, accept: Control+Shift+2, toggle: full_shape }        # 全角/半角切换
    - { when: always, accept: Control+Shift+3, toggle: show_emoji } # emoji候选切换
    - { when: always, accept: Control+Shift+4, select: .next }
```
