### ISSUE TITLE
如何调整竖直方向每一列右边留白？

### ISSUE THREAD

**Issue by nasyxx** [rime/squirrel#726]
如图，水平方向字能够放在中间，而竖直方向不行，看起来是不同字体导致的。应该是最近更新 0.16.0 之后才发生的。

<img width="336" alt="Screenshot 2023-02-06 at 2 23 34 PM" src="https://user-images.githubusercontent.com/5007613/217080809-caea7ec7-8473-4f84-813b-442b1967d944.png">

<img width="503" alt="Screenshot 2023-02-06 at 2 24 09 PM" src="https://user-images.githubusercontent.com/5007613/217080818-cd5b7af0-d043-493c-bc77-fc5194d8c6e5.png">

我试过调整 base_offset，但不能把右边的多余空白去掉，只能在左边增加：

<img width="553" alt="Screenshot 2023-02-06 at 2 45 21 PM" src="https://user-images.githubusercontent.com/5007613/217081171-753ba2d1-8e06-4549-b1e7-89100b7b82e5.png">

我的方案是：

```yaml
nasy_new:
      name: "nasy"
      font_face: "MonoLisa Nasy, STFLGQKJF, STFQLBYTJF, FZLiuGongQuanKaiShuJF, Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      # font_face: "Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      font_point: 18.0
      label_font_face: "MonoLisa Nasy, STFLGQKJF, STFQLBYTJF, FZLiuGongQuanKaiShuJF, Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      # label_font_face: "Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      label_font_point: 17.0
      comment_font_face: "MonoLisa Nasy, STFLGQKJF, STFQLBYTJF, FZLiuGongQuanKaiShuJF, Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      # comment_font_face: "Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      comment_font_point: 17.0
      candidate_list_layout: stacked
      text_orientation: vertical
      inline_preedit: true
      inline_candidate: false
      translucency: true
      mutual_exclusive: false
      corner_radius: 1.0
      border_height: 5.0
      border_width: 5.0
      line_spacing: 2.0
      spacing: 2.0
      # base_offset: 20.0
      alpha: 0.85
      shadow_size: 3.0
      color_space: srgb
      back_color: 0xDCECF3
      candidate_back_color: 0xDCECF3
      candidate_text_color: 0x6E624C
      comment_text_color: 0x709C2F
      label_color: 0x8070FF
      hilited_candidate_back_color: 0xBCDBE5
      hilited_candidate_text_color: 0x998A75
      hilited_comment_text_color: 0x487705  # 0xB50C8C
      hilited_candidate_label_color: 0x487705  # 0xB50C8C
      preedit_back_color: 0xDAF1E8
      text_color: 0x6E624C
      hilited_text_color: 0xD86E624C
```
