### ISSUE TITLE
[BUG] 在Microsoft PowerPoint中，表格内每切换一个单元格，中英文就重置一次

### ISSUE THREAD

**Issue by fhfuih** [rime/squirrel#740]
在最新版的MS PowerPoint中（16.70）新建一个表格，焦点放在第一个格子，切换到英文模式，然后用tab或者鼠标移动焦点到另外的格子，再输入的时候又变成中文模式了。

squirrel配置
```yaml
patch:
  style/+:
    # font_face: "方正屏显雅宋_GBK"
    # font_point: 16
    # label_font_point: 16
    # comment_font_point: 16
    corner_radius: 6
    hilited_corner_radius: 6
    # translucency: true
    alpha: 0.8
    # border_height: 2
    # border_width: 2
    # border_color: 0x00000000
    horizontal: true
    color_scheme: ink
    color_scheme_dark: dark_temple
    candidate_format: "%c %@"
  app_options/net.kovidgoyal.kitty:
    ascii_mode: true
  app_options/com.microsoft.VSCode:
    ascii_mode: true
  app_options/org.zotero.zotero:
    ascii_mode: true
```
