### ISSUE TITLE
[错误]  squirrel 使用 alacritty 终端下无法使用中文符号

### ISSUE THREAD

**Issue by erasin** [rime/squirrel#741]
针对 [Alacritty](https://github.com/alacritty/alacritty) 设置 ascii_mode=false 有效，dan无法输入中文标点，无论如何切换都是英文标点。 

用的 [rime-ice](https://dvel.me/posts/rime-ice/#%e4%bb%a5-patch-%e7%9a%84%e6%96%b9%e5%bc%8f%e6%89%93%e8%a1%a5%e4%b8%81)的方案，使用 patch 补丁方式配置，自定义 squirrel.custom.yaml 配置。 其他的 app 是有效的，只有 org.alacritty 无效。

配置效果： 默认中文， 依然英文标点
```yaml
patch:
  app_options:
    org.alacritty:
      ascii_mode: false
      no_inline: false
```

配置效果： 默认英文， 切换中文后依然英文标点
```yaml
patch:
  app_options:
    org.alacritty:
      ascii_mode: true
      no_inline: true
```

-------------
删除了所有配置，使用rime默认的配置项，依然是同样的效果。
