### ISSUE TITLE
对Mac内置的option+arrowkeys的支持

### ISSUE THREAD

**Issue by Ravenightwing** [rime/squirrel#747]
Mac内置的输入法有option + ←和option+ →两个shortcuts来移动到前一个词，下一个词。请问鼠须管有可能增加这个支持吗？

**Comment by iDvel** [comment]
默认是 Shift + ←→
可以改成 Option：
```yaml
key_binder:
  bindings:
    - { when: composing, accept: Alt+Left, send: Shift+Left }
    - { when: composing, accept: Alt+Right, send: Shift+Right }
```
我觉得 Tab 更好用。
