### ISSUE TITLE
标点默认是英文半角，每次切换成中文标点， 换到别的输入法再换回rime就会重置成英文。

### ISSUE THREAD

**Issue by sviion** [rime/squirrel#750]

**Comment by groverlynn** [comment]
這完全符合設定啊

**Comment by kchen0x** [comment]
输入法状态切换
我们来看一下朙月拼音的方案定义文件 luna_pinyin.schema.yaml，其中有这么一段定义：

```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
```

switches 表示该输入方案可切换的状态。 Rime 会记住输入方案的状态，这样在切换输入法的时候就不会丢失这些状态值。

其中 name 是用来标识一种状态的变量名。该状态变量实际上是 Rime 全局共享的，就是说如果朙月拼音输入方案与地球拼音输入方案都使用同一个状态变量「simplification」来标识简/繁状态，那么当切换朙月拼音为简体输出状态后，再切换到地球拼音输入法，那么也会保持简体输出。

states是可切换状态展示给用户的状态信息。如下图所示：

![image](https://github.com/rime/squirrel/assets/9739009/4b33d575-8929-4f99-873a-c8cc6bb0ec4a)

reset 告诉 Rime 不记住该状态值，每次切换到该输入方案时候都要重置该值，可选值为「0或1」。

这些状态变量会由 engine/translators 或 engine/filters 来捕获，并根据状态变量的值修改候选词列表。比如个过滤器 simplifier 就默认监听「simplification」状态变量来修改候选词的简繁。
