### ISSUE TITLE
vim_mode无法启用

### ISSUE THREAD

**Issue by IIllIIIlll** [rime/squirrel#757]
# 问题描述：

我在`squirrel.custom.yaml`添加了如下配置：

```yaml
com.jetbrains.intellij:
  ascii_mode: true
  vim_mode: true
com.microsoft.VSCode:
  ascii_mode: true
  vim_mode: true
md.obsidian:
  vim_mode: true
```

理想情况是在VS Code中按Esc自动切换到英文模式，但是实际上并没有。

我查阅了最初添加这个功能的commit，代码还在最新的源码中，因此应该是我这里的问题。

我使用的系统版本是13.3.1 (22E261)，鼠须管版本是16.2。

使用的是rimeice方案。

请问我需要进行其他的设置吗？

如果需要我提供其他的信息，请尽管说。

谢谢！
