### ISSUE TITLE
有没有可能实现中英输入对应不同快捷键，而不是一个快捷键切换中英？

### ISSUE THREAD

**Issue by HF706** [rime/squirrel#772]
有没有可能实现中英输入对应不同快捷键，而不是一个快捷键切换中英？
比如像这样，按下 CapsLock 键切换英文输入，按下右 Command 键切换中文输入。而不是一个按键用于切换方案？

**Comment by pdog18** [comment]
https://github.com/rime/home/discussions/1101

https://github.com/rime/home/issues/454

**Comment by LEOYoon-Tsaw** [comment]
可以用不同按鍵，不要用toggle，而用set-option、unset_option。但Capslock和Command非常特殊，我懷疑用不了

**Comment by HF706** [comment]
> 
感谢回复😘。还有一些问题，
我在 default.custom.yaml 中设置如下：
```
patch:
  # 菜单
  menu:
    page_size: 8  # 候选词个数
    # alternative_select_labels: [ ①, ②, ③, ④, ⑤, ⑥, ⑦, ⑧, ⑨, ⑩ ]  # 修改候选项标签
    # alternative_select_keys: ASDFGHJKL  # 如编码字符占用数字键，则需另设选字键
    # ascii_mode、inline、no_inline、vim_mode 等等设定，可参考 /Library/Input Methods/Squirrel.app/Contents/SharedSupport/squirrel.yaml
  # 中西文切换
  #
  # 【good_old_caps_lock】 CapsLock 切换到大写或切换中英。
  # （macOS 偏好设置的优先级更高，如果勾选【使用大写锁定键切换“ABC”输入法】则始终会切换输入法）
  #
  # 切换中英：
  # 不同的选项表示：打字打到一半时按下了 CapsLock、Shift、Control 后： 
  # commit_code  上屏原始的编码，然后切换到英文
  # commit_text  上屏拼出的词句，然后切换到英文
  # clear        清除未上屏内容，然后切换到英文
  # inline_ascii 无输入时，切换中英；有输入时，切换到临时英文模式，按回车上屏后回到中文状态
  # noop         屏蔽快捷键，不切换中英，但不要屏蔽 CapsLock
  ascii_composer:
    good_old_caps_lock: true  # true | false
    switch_key:
      Caps_Lock: noop	# commit_code | commit_text | clear
      Shift_L: noop     # commit_code | commit_text | inline_ascii | clear | noop
      Shift_R: noop     # commit_code | commit_text | inline_ascii | clear | noop
      Control_L: noop   # commit_code | commit_text | inline_ascii | clear | noop
      Control_R: noop   # commit_code | commit_text | inline_ascii | clear | noop
  key_binder/bindings/+:
    - {when: always, accept: Control+Shift+9, set_option: ascii_mode}
  key_binder/bindings/+:
    - {when: always, accept: Control+Shift+0, unset_option: ascii_mode}
```
为什么只有切换为中文生效了呢？
但是当我将下面内容注释，切换英文可以生效，这是为什么？
```
  key_binder/bindings/+:
    - {when: always, accept: Control+Shift+0, unset_option: ascii_mode}
```
