### ISSUE TITLE
rime.lua和lua文件夹未同步

### ISSUE THREAD

**Issue by 4ft35t** [rime/squirrel#786]
同样问题 https://github.com/rime/weasel/issues/831

```yaml
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.16.2
```
