### ISSUE TITLE
请问怎么关闭Caps切换中英文, 让其恢复成大小写切换?

### ISSUE THREAD

**Issue by vosho** [rime/squirrel#811]
请问怎么关闭Caps切换中英文, 让其恢复成大小写切换?
谢谢

---- 
设置成这样没有效果:
`default.custom.yaml`
```
  ascii_composer:
    good_old_caps_lock: true       # true: 在保持 cap 键原有的特征， false: 点击不会切换大小写
    switch_key:
      Caps_Lock: noop # commit_code        # 如果想用 cap 键切换中英文输入，就修改为上面三种的任一一种，否则用 noop
      Shift_L: commit_code          # macOs 上 shift 键不区别左右，设置参数同上
      Shift_R: commit_code
      Control_L: noop
      Control_R: noop
```
