### ISSUE TITLE
Chrome 浏览器地址栏和网页输入框中英切换不同步

### ISSUE THREAD

**Issue by zexi** [rime/squirrel#816]
全新安装没有配置的 squirrel ，打开 Chrome 浏览器，在地址栏切换成了英文，然后聚焦到搜索输入框，又变成了中文。

现象是地址栏输入框和网页里面的 input 输入框中英状态是需要分别设置的，想知道这是故意设计成这样，还是有 bug ？

我在 safari 和 firefox 没有遇到这个问题，只有 Chrome 和 Edge 浏览器有这个问题。下面是 Chrome 中这个现象的录屏。

https://github.com/rime/squirrel/assets/10767027/80ca96a3-ed38-4667-86d2-f299114ab7ff

这个是 squirrel 版本：

```yaml
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.16.2
install_time: "Fri Oct 27 12:18:35 2023"
installation_id: "9967e06c-1316-455f-a5a1-4204ef62621f"
rime_version: 1.8.5%
```

Chrome 版本：Version 118.0.5993.117 (Official Build) (arm64)
macOS 版本：Sonoma 14.0
