### ISSUE TITLE
远程控制时shift切换中英文和字母上屏都失效

### ISSUE THREAD

**Issue by AoEiuV020** [rime/squirrel#825]
我用的parsec是这样，另外用过rustdesk两种键盘模式中的传统模式也这样，但1:1模式就正常，系统自带vnc也正常，不知道是什么区别，
我的设置，本地shift正常工作，切换中英文同时字母上屏，但远程控制就可能无效，
https://github.com/AoEiuV020/rime-wubi86-jidian/blob/master/default.custom.yaml
```
  ascii_composer:
    good_old_caps_lock: true       # true: 在保持 cap 键原有的特征， false: 点击不会切换大小写
    switch_key:
      Caps_Lock: commit_code        # 如果想用 cap 键切换中英文输入，就修改为上面三种的任一一种，否则用 noop
      Shift_L: commit_code          # macOs 上 shift 键不区别左右，设置参数同上
      Shift_R: commit_code
      Control_L: noop
      Control_R: noop
```
另外注意到远程控制时mac的“虚拟键盘”有响应到shift，所以肯定不是远程控制软件本身没发shift，
