### ISSUE TITLE
一个关于 key_binder/bindings 按键绑定的疑问

### ISSUE THREAD

**Issue by gradypark86** [rime/squirrel#849]
请问 `key_binder/bindings` 中如何将绑定到数字（字母区上方数字区）？

我通过
```
- {accept: KP_1, send: 1, when: always}
```
试图将小键盘区的 `1` 指向字母 `Q` 上方的 `1`，以完成 #144 的相关设置，但是如此设置后键入小键盘 `1` 没有任何输出。
而如果将该语句改为
```
- {accept: KP_1, send: a, when: always}
```
则可以将键入小键盘区的 `1` 指向字母 `a`，正常上屏 `a`。

那么如果想指向数字 1，`send:` 中应该使用什么参数呢？非常感谢。

**Comment by buunnp** [comment]
我也想请教类似的问题。我尝试自定义一个输入方案，通过按键映射，临时模拟一个数字小键盘，以便录入数字。最简单的方案就是把uio三个键分别映射成456，jkl映射成123，结合上方789键就有数字小键盘了。但是设置好key_binder/bindings后，数字不上屏，原按键确实被捕捉到了，比如按下j，不会输入j，但也没有任何其它反应。配置文件如下：
```
# Rime schema
# encoding: utf-8

# 方案说明
schema:
  schema_id: num_pad
  name: "数字键盘"
  version: "26.03.26"
  description: |
    按键映射，将字母键映射为数字。

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators: 
    - punct_translator 
  filters: 
    - uniquifier   

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz"

key_binder:
  bindings:
    # 以下为按键映射示例
    # 按下 j 输出 1
    - { accept: "j", send: 1, when: always }
    # 按下 k 输出 2
    - { accept: "k", send: 2, when: always }
    # 按下 l 输出 3
    - { accept: "l", send: "3", when: always }
    # 按下 u 输出 4
    - { accept: "u", send: "4", when: always }
    # 按下 i 输出 5
    - { accept: "i", send: "5", when: always }
    # 按下 o 输出 6
    - { accept: "o", send: "6", when: always }

    # 其他常用功能绑定示例（如切换中英文）
    - { when: always, accept: "Shift_L", toggle: ascii_mode }  # 左Shift切换中英文[[3]]

recognizer:
  patterns:
    punct: "^/([0-9]0?|[A-Za-z]+)$"

punctuator:
  import_preset: symbols

# 以下为方案的其他基本设置
menu:
  page_size: 5

switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "英文"]
```

**Comment by lotem** [comment]
`send` 之後的參數是發給輸入法處理的按鍵，不是輸出的字符。

> 按下 j 输出 1

不是這個意思。不能保證輸出 1。除非方案本身會處理數字鍵 1 ，並輸出字符 1。

如果用戶按鍵盤上的數字鍵 1，而方案沒有定義如何處理數字鍵 1，輸入法不會做任何動作，而是由操作系統做默認處理。

現在用戶在鍵盤上按了 j 鍵，輸入法處理了 j 鍵，發送給自己數字鍵 1，然後輸入法不處理——不是字母、speller 不處理；未定義爲標點符號，punctuator 不處理；此時沒有候選字，selector 不處理——輸入法不會做任何動作。輸入法已經處理了 j 鍵，操作系統不需要上屏字符 j。

**Comment by lotem** [comment]
> 小键盘 `1` 没有任何输出

輸入方案沒有定義遇到這個鍵要輸出文字。
綁定按鍵是重發一個數字鍵給自己處理。輸入法不能向系統發送按鍵，只能輸出文字。

**Comment by lotem** [comment]
> 我尝试自定义一个输入方案，通过按键映射，临时模拟一个数字小键盘，以便录入数字。最简单的方案

最簡單的方案是用可編程（自定義鍵位）的鍵盤。

**Comment by buunnp** [comment]
@lotem 感谢如此迅速的答复！刚想来补充rime版本号，以为是什么bug，看来还是对rime的机制不熟悉。从你答复来看，我猜还是有可能实现，只是需要额外的配置让rime把“1”送给操作系统。我再研究研究。

**Comment by lotem** [comment]
我建议客制化键盘。你可以把数字定义成标点符号，但这是输出文字，毕竟和真正的数字键盘不一样。假如应用程序接收的是数字按键而不是字符呢？客制化键盘才能够模拟真正的数字小键盘。而且不依赖软件。

**Comment by buunnp** [comment]
确实，如果有很多数字录入的话，还是小键盘好用。我是偶尔有这样的需求，想着有没有软件可以解决。mac上专门的按键设置软件 Karabiner-Elements也是好用的，只是平时又不用，不想让它后台跑一堆东西，还占一个menu bar的位置😄
经过@lotem 提示，我的需求解决了，在标点符号处理部分将数字上屏。下面是可用的输入方案，需要用时，切输入法方案就可以了。
```
# Rime schema
# encoding: utf-8

# 方案说明
schema:
  schema_id: num_pad
  name: "模拟数字键盘"
  version: "26.03.26"
  author:
    - buunnp
  description: |
    按键映射，将字母键映射为数字。

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators: 
    - punct_translator 
  filters: 
    - uniquifier   

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz"

key_binder:
  bindings:
    # 以下为按键映射
    - { accept: "j", send: 1, when: always }
    - { accept: "k", send: 2, when: always }
    - { accept: "l", send: 3, when: always }
    - { accept: "u", send: 4, when: always }
    - { accept: "i", send: 5, when: always }
    - { accept: "o", send: 6, when: always }

recognizer:
  patterns:
    punct: "^/([0-9]0?|[A-Za-z]+)$"

punctuator:
  # 在处理标点符号部分将数字上屏
  half_shape:
      "1": "1"
      "2": "2"
      "3": "3"
      "4": "4"
      "5": "5"
      "6": "6"

# 以下为方案的其他基本设置
menu:
  page_size: 5

switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "英文"]
```
