### ISSUE TITLE
Action 版本的 Squirrel，配置个性化字体，如果 comment_font_face 名称不对将造成 Squirrel 配置错误

### ISSUE THREAD

**Issue by Mintimate** [rime/squirrel#850]
发现一个问题，使用Action版本的Squirrel，配置个性文件；

如果设置的`comment_font_face`配置错误，那么鼠须管的配置将出错，如果碰巧是第一次部署，就会无法使用输入法。
```yaml
# 无法使用的情况
  # 注释字体及大小
  comment_font_face: "PingFang"  
  comment_font_point: 14  
```
如果没有设置`comment_font_face`，但是设置了`font_face`，且`font_face`指向的字体名称不正确，那么也是相同的情况。
```yaml
# 无法使用的情况
  # 注释字体及大小
  font_face: "PingFang"
  font_point: 16
```

但是，如果设置了`comment_font_face`指向的字体名称是对的，那么即使`font_face`指向错误，也不影响输入法的部署和使用。
```yaml
# 可以使用的情况
  # 全局字体及大小
  font_face: "PingFang"
  font_point: 16
  # 序号字体及大小
  label_font_face: "PingFang"    
  label_font_point: 16
  # 注释字体及大小
  comment_font_face: "PingFang SC"  
  comment_font_point: 14  
```

在`release`版本上不存在这个问题；似乎是判断字体不存在后，会用系统默认字体。
