### ISSUE TITLE
就为vim_mode添加esc以外的其它按键支持

### ISSUE THREAD

**Issue by free-150** [rime/squirrel#864]
目前测试鼠须管 vim_mode 只支持esc 而不支持 <C-[>, <C-c>, <C-C> 。小狼毫却可以完美支持：https://github.com/rime/weasel/pull/1047

**Comment by ksqsf** [comment]
应该是支持的

https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L200-L204

**Comment by free-150** [comment]
- 版本：最新夜版
- mac版本：14.4.1
但是我这里确实不行。只有按esc是有效的，squirrel.yaml内容：
```yaml
app_options:   
  com.microsoft.VSCode:
    ascii_mode: true
    ascii_punct: true

  com.vscodium:
    ascii_mode: true
    ascii_punct: true

  com.apple.dt.Xcode:
    ascii_mode: true
    ascii_punct: true

  com.googlecode.iterm2:
    ascii_mode: true
    vim_mode: true
```
