### ISSUE TITLE
Squirrel 变更 app_options 之后是否必须重启或重新登录才能生效？

### ISSUE THREAD

**Issue by shelken** [rime/squirrel#869]
系统：14.4.1

in squirrel.custom.yaml
```yaml
patch:
  app_options:
    com.raycast.macos:
      ascii_mode: true
```

变更 app_options 必须重启或者重登才能生效。

是否有使用命令重启输入法的方式
