### ISSUE TITLE
[Bug] UI 设置皮肤内配置不生效

### ISSUE THREAD

**Issue by cbconne** [rime/squirrel#912]
**簡要描述 Bug：**
（簡單地描述你遇到的 Bug）
UI 设置皮肤内配置不生效，按照描述是`  # 预设选项。如果皮肤没写，则使用这些属性；如果皮肤写了，使用皮肤的。`，但实测仍然是以预设选项为准

**預期行爲：**
皮肤内存在配置项时以皮肤配置内容为准

**實際行爲：**
皮肤内配置项不生效，仅以预设选项为准

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

![image](https://github.com/rime/squirrel/assets/44186296/812b279f-c50f-4736-9ddc-8c7a0339b8c3)

**Comment by cbconne** [comment]
发现是特定配置项问题，inline_preedit确实是以皮肤内配置为准的

**Comment by LEOYoon-Tsaw** [comment]
確實漏了這倆，也唯獨漏了這倆

**Comment by HomeQi** [comment]
我也遇到类似的问题，使用自定义的配置无法生效，是不是现在升级了新的配置方法？我和楼主的配置方式好像不大一样。
```
patch:
  show_notifications_when: appropriate     # 状态通知，可设为全开（always）全关（never）  

  # 皮肤主题名称输入在下方，分为浅色和深色
  # 浅色主题
  style/color_scheme: wechat_light
  # 深色主题
  style/color_scheme_dark: wechat_dark

  # 皮肤主题
  preset_color_schemes:
    wechat_light:
      name: 微信键盘浅色
      horizontal: true                          # true横排，false竖排
      back_color: 0xFFFFFF                      # 候选条背景色
      border_height: 0                          # 窗口上下高度，大于圆角半径才生效
      border_width: 8                           # 窗口左右宽度，大于圆角半径才生效
      candidate_format: "%c %@ "                # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      comment_text_color: 0x999999              # 拼音等提示文字颜色
      corner_radius: 5                          # 窗口圆角
      hilited_corner_radius: 5                  # 高亮圆角
      font_face: PingFangSC                     # 候选词字体
      font_point: 20                            # 候选字大小
      hilited_candidate_back_color: 0x75B100    # 第一候选项背景色
      hilited_candidate_text_color: 0xFFFFFF    # 第一候选项文字颜色
      label_font_point: 16                      # 候选编号大小
      text_color: 0x424242                      # 拼音行文字颜色
      inline_preedit: true                      # 拼音位于： 候选框 false | 行内 true

    wechat_dark:
      name: 微信键盘深色
      horizontal: true                          # true横排，false竖排
      back_color: 0x2e2925                      # 候选条背景色
      border_height: 0                          # 窗口上下高度，大于圆角半径才生效
      border_width: 8                           # 窗口左右宽度，大于圆角半径才生效
      candidate_format: "%c %@ "                # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      comment_text_color: 0x999999              # 拼音等提示文字颜色
      corner_radius: 5                          # 窗口圆角
      hilited_corner_radius: 5                  # 高亮圆角
      font_face: PingFangSC                     # 候选词字体
      font_point: 20                            # 候选字大小
      hilited_candidate_back_color: 0x75B100    # 第一候选项背景色
      hilited_candidate_text_color: 0xFFFFFF    # 第一候选项文字颜色
      label_font_point: 16                      # 候选编号大小
      text_color: 0x424242                      # 拼音行文字颜色
      label_color: 0x999999                     # 预选栏编号颜色
      candidate_text_color: 0xe9e9ea            # 预选项文字颜色
      inline_preedit: true                      # 拼音位于： 候选框 false | 行内 true
```
