### ISSUE TITLE
[Bug] 1.0 版本 label_font_point 不生效

### ISSUE THREAD

**Issue by xiehuc** [rime/squirrel#915]
**簡要描述 Bug：**
（簡單地描述你遇到的 Bug）

<img width="506" alt="截屏2024-05-31 10 42 12" src="https://github.com/rime/squirrel/assets/571878/75011a40-64ad-49f2-b8df-bef2d4370550">

主题里面配了的，style下面配了的，均不生效

```
  preset_color_schemes/macos_light:
    name: Mac 仿原生亮色/macos_light
    author: 一方
    color_space: display_p3
    back_color: 0x6BFFFFFF # 候选条背景色，24 位色值，16 进制，BGR 顺序
    text_color: 0x424242 # 拼音行文字颜色
    hilited_text_color: 0x3c3c3c # 高亮拼音 (需要开启内嵌编码)

    hilited_candidate_back_color: 0xD75A00 # 第一候选项背景背景色
    hilited_candidate_text_color: 0xFFFFFF # 第一候选项文字颜色
    hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色

    hilited_comment_text_color: 0x999999 # 注解文字高亮
    candidate_text_color: 0x3c3c3c # 预选项文字颜色
    comment_text_color: 0x999999 # 拼音等提示文字颜色
    inline_preedit: true # 单行显示，false 双行显示
    #label_color: 0x999999   # 预选栏编号颜色
    label_color: 0xBB333333
    candidate_format: "[label]. [candidate] [comment]" # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
    # font_face: "Sarasa Mono SC Nerd Font" # 候选词编号字体
    # label_font_face: "SFCompactText-Regular" # 候选词编号字体
    label_font_face: "PingFangSC" # 候选词编号字体
    font_point: 17 # 候选文字大小
    label_font_point: 13 # 候选编号大小
    corner_radius: 5 # 候选条圆角
    hilited_corner_radius: 5 # 高亮圆角
    border_height: 0 # 窗口上下高度
    border_width: 5 # 窗口左右宽度
    line_spacing: 0
    base_offset: 2
    border_color_width: 0 # 输入条边框宽度
    translucency: true

```

**預期行爲：**

**實際行爲：**

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告
