### ISSUE TITLE
[Bug] 1.0 text_orientation在皮肤中无法生效

### ISSUE THREAD

**Issue by pengchaocol** [rime/squirrel#916]
**簡要描述 Bug：**
如果使用如下的配置，候选字依然是竖排
必须将以下的内容放在style中才可以横排
```
    candidate_list_layout: linear
    text_orientation: horizontal  # horizontal | vertical
```

```
patch:
  app_options:
    com.runningwithcrayons.Alfred:
      ascii_mode: true    # 开启默认英文
    com.googlecode.iterm2:
      ascii_mode: true
      # ascii_mode: true  # 初始爲西文模式
      # no_inline: true   # 不使用行內編輯
      # vim_mode: true    # 退出VIM插入模式自動切換輸入法狀態
  style:
    # 选择皮肤，亮色与暗色主题
    color_scheme: wechat_light
    color_scheme_dark: wechat_light
  preset_color_schemes:
    wechat_light:
      name: "微信浅色／Wechat Light"
      author: 小码哥
      font_face: "Yahei Mono,PingFangSC-Regular,PingFangSC"          # 字体及大小
      font_point: 16
      label_font_face: "Yahei Mono,PingFangSC-Regular,PingFangSC"    # 序号字体及大小
      label_font_point: 13
      comment_font_face: "Yahei Mono,PingFangSC-Regular,PingFangSC"  # 注字体及大小
      comment_font_point: 1
      # candidate_format: "%c\u2005%@\u2005" # 编号 %c 和候选词 %@ 前后的空间
      candidate_format: "[label].[candidate]"
      candidate_list_layout: linear   # 候选排布：层叠 stacked | 行 linear
      text_orientation: horizontal    # 行文向： 横 horizontal | 纵 vertical
      inline_preedit: true            # 拼音位于： 候选框 false | 行内 true
      translucency: false             # 磨砂： false | true
      mutual_exclusive: false         # 色不叠加： false | true
      border_height: 1                # 外边框 高
      border_width: 1                 # 外边框 宽
      corner_radius: 5                # 外边框 圆角半径
      hilited_corner_radius: 5       # 选中框 圆角半径
      surrounding_extra_expansion: 12 # 候选项背景相对大小？
      shadow_size: 0                 # 阴影大小
      line_spacing: 5                # 行间距
      base_offset: 0                 # 字基高
      alpha: 1                       # 透明度，0~1
      spacing: 10                    # 拼音与候选项之间的距离 （inline_preedit: false）
      color_space: srgb                       # 色彩空间： srgb | display_p3
      back_color: 0xFFFFFF                    # 底色
      hilited_candidate_back_color: 0x79af22  # 选中底色
      label_color: 0x999999                   # 序号颜色
      hilited_candidate_label_color: 0xFFFFFF # 选中序号颜色
      candidate_text_color: 0x3c3c3c          # 文字颜色
      hilited_candidate_text_color: 0xFFFFFF  # 选中文字颜色
      comment_text_color: 0x999999            # 注颜色
      hilited_comment_text_color: 0x999999    # 选中注颜色
      text_color: 0x424242                    # 拼音颜色 （inline_preedit: false）
      hilited_text_color: 0x999999            # 选中拼音颜色 （inline_preedit: false）
      candidate_back_color: 0xFFFFFF          # 候选项底色
      # preedit_back_color:                   # 拼音底色 （inline_preedit: false）
      hilited_back_color: 0x79af22            # 选中拼音底色 （inline_preedit: false）
      border_color: 0xFFFFFF                  # 外边框颜色
```
**預期行爲：**

**實際行爲：**

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [x] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告
