### ISSUE TITLE
[Bug] 皮肤配置会跟随macOS黑白模式

### ISSUE THREAD

**Issue by RoyRao2333** [rime/squirrel#923]
**簡要描述 Bug：**

v1.0.1后，鼠须管的皮肤会跟随系统的黑白模式吗？

系统为 light appearance 时：

<img width="680" alt="image" src="https://github.com/rime/squirrel/assets/31413093/bdf181a8-926e-4022-ab6f-872de1fe0db0">

系统为 dark appearance 时：

<img width="322" alt="image" src="https://github.com/rime/squirrel/assets/31413093/a34b0b8e-7fa7-4e3c-a09b-82f322bb9c7e">

**預期行爲：**

希望：

1. 皮肤UI不要跟随系统，锁死一个样式。
2. 或者请告诉我在哪里可以分别配置黑白模式的皮肤呢？

**環境**
 - 系統版本：macOS 14.5
 - 鼠鬚管版本：v1.0.1
 - 方案：朙月拼音-简化字
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**squirrel.custom.yaml**

```yaml
patch:
  show_notifications_when: appropriate     # 状态通知，可设为全开（always）全关（never）  
  
  # 以下软件默认英文模式
  app_options:
    com.apple.dt.Xcode:
      ascii_mode: true
    com.jetbrains.intellij:
      ascii_mode: true
    com.jetbrains.datagrip:
      ascii_mode: true
    com.jetbrains.pycharm:
      ascii_mode: true
    com.jetbrains.WebStorm:
      ascii_mode: true
    com.jetbrains.WebStorm-EAP:
      ascii_mode: true
    com.microsoft.VSCode:
      ascii_mode: true
    dev.warp.Warp-Stable:
      ascii_mode: true
      ascii_punct: true
    com.apple.Terminal:
      ascii_mode: true
      ascii_punct: true
    com.apple.finder:
      ascii_mode: true
    com.apple.calculator:
      ascii_mode: true
    com.apple.launchpad.launcher:
      ascii_mode: true
    com.apple.systempreferences:
      ascii_mode: true
    com.apple.ActivityMonitor:
      ascii_mode: true
    com.apple.keychainaccess:
      ascii_mode: true
    com.apple.Spotlight:
      ascii_mode: true
    org.alacritty:
      ascii_mode: true
    com.github.wez.wezterm:
      ascii_mode: true

  # 皮肤主题名称输入在下方，开启去掉前面#
  style/color_scheme: purity_of_essence

  # 皮肤主题
  preset_color_schemes:
  
    purity_of_essence:
      author: "佛振"
      inline_preedit: true
      # horizontal: true
      corner_radius: 5
      font_point: 16
      back_color: 0xfafafa
      # candidate_format: "%c %@ "
      candidate_format: "[label]. [candidate] [comment]"
      candidate_text_color: 0x000000
      comment_text_color: 0x808080
      hilited_back_color: 0xfafafa
      hilited_candidate_back_color: 0x444444
      hilited_candidate_text_color: 0xeeeeee
      hilited_text_color: 0x000000
      name: "純粹的本質／Purity of Essence"
      text_color: 0x2c2ccc
      candidate_list_layout: "linear"
      text_orientation: "horizontal"
```
