### ISSUE TITLE
[Bug] 更新1.01后皮肤设置不起作用

### ISSUE THREAD

**Issue by KeqiZeng** [rime/squirrel#924]
**簡要描述 Bug：**
（簡單地描述你遇到的 Bug）

我的`squirrel.custom.yaml`:
```yaml
# squirrel.custom.yaml
patch:
  app_options: {}
  style:
    candidate_list_layout: linear # stacked | linear
    text_orientation: horizontal
    inline_preedit: true
    color_scheme: panda
  preset_color_schemes:
    panda:
      name: Panda
      author: Ketch
      corner_radius: 5
      font_face: PingFangSC
      font_point: 20
      label_font_face: PingFangSC
      label_font_point: 20
      back_color: '0xF1F1F1'
      text_color: '0x2E2E2E'
      hilited_text_color: '0xEAEAEA'
      hilited_back_color: '0x2E2E2E'
      hilited_candidate_text_color: '0xF1F1F1'
      hilited_candidate_back_color: '0x2E2E2E'
      hilited_candidate_label_color: '0xF1F1F1'
      hilited_comment_text_color: '0xF1F1F1'
      candidate_text_color: '0x2E2E2E'
      label_color: '0x2E2E2E'
      comment_text_color: '0x2E2E2E'
```
实际皮肤效果看起来却没有受到自定义的影响：

![image](https://github.com/rime/squirrel/assets/75246050/0a104f5b-9224-4fdd-bb10-7e58bdc6e243)

尽管我将`color_scheme`设置成内置的皮肤如`ink`或`luna`等，依然不起作用

**預期行爲：**
皮肤设置正常工作

**實際行爲：**
皮肤设置完全不起作用

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.1)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [x] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告
