### ISSUE TITLE
[Bug]无法使用shift在英文输入法时输入大写字母

### ISSUE THREAD

**Issue by HeMuling** [rime/squirrel#932]
**簡要描述 Bug：**
（簡單地描述你遇到的 Bug）
无法使用shift在英文输入法时输入大写字母，而在中文输入法则可以顺利打出大写

**預期行爲：**
在英文输入法下，shift+英文字母可以输入大写字母

**實際行爲：**
在英文输入法下，shift+英文字母只能输入小写字母

**環境**
 - 系統版本： macOS 14.5 (23F79)
 - 鼠鬚管版本： 1.0.1

这个bug在[0.16.2](https://github.com/rime/squirrel/releases/tag/0.16.2)中没有，更新到1.0.1后出现的

在`default.yaml`中，启用：
```
ascii_composer:
  good_old_caps_lock: false  # true | false
  switch_key:
    Caps_Lock: commit_code      # commit_code | commit_text | clear
    Shift_L: commit_code  # commit_code | commit_text | inline_ascii | clear | noop
    Shift_R: noop         # commit_code | commit_text | inline_ascii | clear | noop
    Control_L: noop       # commit_code | commit_text | inline_ascii | clear | noop
    Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop
```

在`squirrel.custom.yaml`中，启用：
```
mojave_dark:
      name: "沙漠夜／Mojave Dark"
      author: "xiehuc <xiehuc@gmail.com>"
      text_orientation: horizontal  # horizontal | vertical
      candidate_list_layout: linear
      inline_preedit: false
      candidate_format: "%c %@"
      corner_radius: 5
      hilited_corner_radius: 0
      border_height: 6
      border_width: 12
      border_color_width: 0
      font_face: PingFangSC
      font_point: 16
      label_font_point: 13
      text_color: 0xdedddd
      back_color: 0x3c3c3c
      label_color: 0x888785
      border_color: 0x3c3c3c
      candidate_text_color: 0xdedddd
      hilited_text_color: 0xdedddd
      hilited_back_color: 0x3c3c3c
      hilited_candidate_text_color: 0xefefef
      # hilited_candidate_back_color: 0xcb5d00
      hilited_candidate_label_color: 0xefefef
      comment_text_color: 0xdedddd
```
根据[皮肤失效处理](https://github.com/rime/squirrel/issues/923#issuecomment-2143439348)且在末尾处增添：
```
patch:
  style/color_scheme: mojave_dark
  style/color_scheme_dark: mojave_dark
```
