### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hotleave** [rime/squirrel#934]
**簡要描述 Bug：**
native 配色在系统是深色主题时显示的还是浅色

**預期行爲：**
在深色主题时显示深色，在浅色主题时显示浅色

**實際行爲：**

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： 声笔飞讯(https://github.com/sbsrf/home)

**我試過：**
  - [x] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [x] 這是個新 Bug，1.0.1 的时候是native在深色主题下是深色的

**Comment by LEOYoon-Tsaw** [comment]
得把color_scheme_dark也設成native

**Comment by hotleave** [comment]
设置成 solarized_dark 是正常的，但设置成 native 就会变回浅色主题，#939 里提到的不保存窗口状态重启不知道如何操作，直接重启不生效
```yaml
patch:
  style/color_scheme: native
  style/color_scheme_dark: native
  #style/color_scheme_dark: solarized_dark
  style/candidate_list_layout: linear
  style/candidate_format: '[candidate] [comment]'
```
