### ISSUE TITLE
固定一部分字词的顺序，其它的词和自造词可以调频的方法

### ISSUE THREAD

**Issue by twz915** [rime/squirrel#97]
当不使用调频时，打五笔 98 时 输入 p
1. 这   2. 之
一直是这个顺序，但是开了调频后，输入 p 可能会之跑到最前面，这样
1. 之  2.这
我想要 “这” 永远在 “之” 前面，而且支持其它的词调频，应该怎么做呢？

98五笔可以参见这里：https://github.com/shrekuu/rime-wubi98

**Comment by jakwings** [comment]
請參考：
https://github.com/rime/home/issues/9#issuecomment-103568916

**Comment by twz915** [comment]
@jakwings  我设置了没有效果，能不能给一个具体点的例子呢？

**Comment by jakwings** [comment]
直接修改 wubi98.dict.yaml 加上很高的字頻應該就好了，不過我試了下好像沒什麼特别的效果……

**Comment by twz915** [comment]
现在的问题是，开启调频的话，原来 dict.yaml 中的 weight 就没用了

**Comment by jakwings** [comment]
除了修改字頻之外，你再改一下 scheme.yaml 禁止單碼字調頻：

```yaml
translator:
  ...
  disable_user_dict_for_patterns:
    - ^[a-x]$
````
