### ISSUE TITLE
[BUG]更新到1.02之后 squirrel.custom.yaml似乎不起作用了

### ISSUE THREAD

**Issue by LanSnowZ** [rime/squirrel#982]
```
patch:
  show_notifications_when: never     # 状态通知，可设为全开（always）全关（never）  
  # show_notifications_when: appropriate     # 状态通知，可设为全开（always）全关（never）  

  # 皮肤主题名称输入在下方，分为浅色和深色
  # 浅色主题
  style/color_scheme: mac_light
  # 深色主题
  style/color_scheme_dark: mac_light

  # 皮肤主题
  preset_color_schemes:
    wechat_light:
      name: 微信键盘浅色
      horizontal: true                          # true横排，false竖排
      back_color: 0xFFFFFF                      # 候选条背景色
      border_height: 0                          # 窗口上下高度，大于圆角半径才生效
      border_width: 8                           # 窗口左右宽度，大于圆角半径才生效
      candidate_format: "%c %@ "                # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      comment_text_color: 0x999999              # 拼音等提示文字颜色
      corner_radius: 5                          # 窗口圆角
      hilited_corner_radius: 5                  # 高亮圆角
      font_face: PingFangSC                     # 候选词字体
      font_point: 16                            # 候选字大小
      hilited_candidate_back_color: 0x75B100    # 第一候选项背景色
      hilited_candidate_text_color: 0xFFFFFF    # 第一候选项文字颜色
      label_font_point: 12                      # 候选编号大小
      text_color: 0x424242                      # 拼音行文字颜色
      inline_preedit: true                      # 拼音位于： 候选框 false | 行内 true

    wechat_dark:
      name: 微信键盘深色
      horizontal: true                          # true横排，false竖排
      back_color: 0x2e2925                      # 候选条背景色
      border_height: 0                          # 窗口上下高度，大于圆角半径才生效
      border_width: 8                           # 窗口左右宽度，大于圆角半径才生效
      candidate_format: "%c %@ "                # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      comment_text_color: 0x999999              # 拼音等提示文字颜色
      corner_radius: 5                          # 窗口圆角
      hilited_corner_radius: 5                  # 高亮圆角
      font_face: PingFangSC                     # 候选词字体
      font_point: 16                            # 候选字大小
      hilited_candidate_back_color: 0x75B100    # 第一候选项背景色
      hilited_candidate_text_color: 0xFFFFFF    # 第一候选项文字颜色
      label_font_point: 12                      # 候选编号大小
      text_color: 0x424242                      # 拼音行文字颜色
      label_color: 0x999999                     # 预选栏编号颜色
      candidate_text_color: 0xe9e9ea            # 预选项文字颜色
      inline_preedit: true                      # 拼音位于： 候选框 false | 行内 true

    mac_light:
      name: Mac浅色
      horizontal: true             # true横排，false竖排
      candidate_format: "%c %@ "   # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角
      hilited_corner_radius: 5                     # 高亮圆角
      line_spacing: 10                             # 行间距(适用于竖排)
      border_height: 4                             # 窗口上下高度，大于圆角半径才生效
      border_width: 4                              # 窗口左右宽度，大于圆角半径才生效
      font_face: "PingFangSC"                      # 候选词字体
      font_point: 16                               # 候选字大小
      label_font_point: 13                         # 候选编号大小
      text_color: 0x424242                    # 拼音行文字颜色
      back_color: 0xFFFFFF                    # 候选条背景色
      border_color: 0xFFFFFF                  # 边框色
      label_color: 0x999999                   # 预选栏编号颜色
      candidate_text_color: 0x3c3c3c          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0xD75A00            # 第一候选项背景背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮

    mac_dark:
      name: Mac深色
      horizontal: true             # true横排，false竖排
      candidate_format: "%c %@ "   # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角
      hilited_corner_radius: 5                     # 高亮圆角
      line_spacing: 10                              # 行间距(适用于竖排)
      border_height: 4                             # 窗口上下高度，大于圆角半径才生效
      border_width: 4                              # 窗口左右宽度，大于圆角半径才生效 
      font_face: "PingFangSC"                      # 候选词字体
      font_point: 16                               # 候选字大小
      label_font_point: 13                         # 候选编号大小
      text_color: 0x424242                    # 拼音行文字颜色
      back_color: 0x252a2e                    # 候选条背景色
      border_color: 0x050505                  # 边框色
      label_color: 0x999999                   # 预选栏编号颜色
      candidate_text_color: 0xe9e9ea          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0xD75A00            # 第一候选项背景背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮

    mac_green:
      name: Mac绿
      horizontal: true             # true横排，false竖排
      candidate_format: "%c %@ "   # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角
      hilited_corner_radius: 5                     # 高亮圆角
      line_spacing: 10                              # 行间距(适用于竖排)
      border_height: 4                             # 窗口上下高度，大于圆角半径才生效
      border_width: 4                              # 窗口左右宽度，大于圆角半径才生效
      font_face: "PingFangSC"                      # 候选词字体
      font_point: 16                               # 候选字大小
      label_font_point: 13                         # 候选编号大小
      text_color: 0x424242                    # 拼音行文字颜色
      back_color: 0xFFFFFF                    # 候选条背景色
      border_color: 0xFFFFFF                  # 边框色
      label_color: 0x999999                   # 预选栏编号颜色
      candidate_text_color: 0x3c3c3c          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      hilited_candidate_back_color: 0x32A14C  # 第一候选项背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮

    mac_orange:
      name: Mac橙
      horizontal: true             # true横排，false竖排
      candidate_format: "%c %@ "   # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角
      hilited_corner_radius: 5                     # 高亮圆角
      line_spacing: 10                              # 行间距(适用于竖排)
      border_height: 4                             # 窗口上下高度，大于圆角半径才生效
      border_width: 4                              # 窗口左右宽度，大于圆角半径才生效
      font_face: "PingFangSC"                      # 候选词字体
      font_point: 16                               # 候选字大小
      label_font_point: 13                         # 候选编号大小
      text_color: 0x424242                    # 拼音行文字颜色
      back_color: 0xFFFFFF                    # 候选条背景色
      border_color: 0xFFFFFF                  # 边框色
      label_color: 0x999999                   # 预选栏编号颜色
      candidate_text_color: 0x3c3c3c          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      hilited_candidate_back_color: 0x0E6BD8  # 第一候选项背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮

    mac_blue:
      name: Mac浅蓝
      horizontal: false              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角
      font_face: "PingFangSC"                      # 候选词字体
      font_point: 16                               # 候选字大小
      label_font_point: 13                         # 候选编号大小
      line_spacing: 10                              # 行间距(适用于竖排)
      text_color: 0x424242                    # 拼音行文字颜色
      back_color: 0xFFFFFF                    # 候选条背景色
      border_color: 0xFFFFFF                  # 边框色
      label_color: 0x999999                   # 预选栏编号颜色
      candidate_text_color: 0x3c3c3c          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0xF8AA4D            # 第一候选项背景背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮

    psionics:
      name: 幽能
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角 
      font_point: 16                               # 候选文字大小
      label_font_point: 14                         # 候选编号大小
      line_spacing: 10                              # 行间距(适用于竖排)
      font_face: "PingFangSC-Regular,HanaMinB"     # 候选词字体  
      text_color: 0xc2c2c2                     # 拼音行文字颜色
      back_color: 0x444444                     # 候选条背景色，24位色值，16进制，BGR顺序
      candidate_text_color: 0xeeeeee           # 预选项文字颜色
      hilited_candidate_back_color: 0xd4bc00   # 候选文字背景色
      comment_text_color: 0x808080             # 拼音等提示文字颜色
      hilited_text_color: 0xeeeeee             # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0x444444             # 第一候选项背景背景色
      hilited_candidate_label_color: 0xfafafa  # 第一候选项编号颜色
      hilited_candidate_text_color: 0xfafafa   # 第一候选项文字颜色
      hilited_comment_text_color: 0x444444     # 注解文字高亮

    win10:
      horizontal: true                  # true横排，false竖排
      candidate_format: "%c %@  "       # 如果是竖排建议改为 "%c\u2005%@"
      font_point: 17              # 候选文字大小
      label_font_point: 16        # 候选编号大小
      corner_radius: 0            # 候选条圆角
      border_width: 6             # 窗口左右宽度
      border_height: 6            # 窗口左右高度
      margin_x: 12                # 字起始距左边距离
      margin_y: 12                # 字上下边距
      spacing: 10                 # 间距
      candidate_spacing: 24       # 候选字间隔
      hilite_spacing: 8           # 序号和候选字之间的间隔
      hilite_padding: 12          # 候选字背景色色块高度 若想候选字背景色块无边界填充候选框，仅需其高度和候选字上下边距一致即可
      round_corner: 0             # 候选字背景色块圆角幅度
      line_spacing: 10            # 行间距(适用于竖排)
      candidate_text_color: 0x000000          # 预选项文字颜色
      comment_text_color: 0x888888            # 拼音等提示文字颜色
      text_color: 0x000000                    # 拼音行文字颜色
      back_color: 0xffffff                    # 候选条背景色，24位色值，16进制，BGR顺序
      hilited_text_color: 0x000000            # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0xffffff            # 第一候选项背景背景色
      hilited_candidate_text_color: 0xffffff  # 第一候选项文字颜色
      hilited_candidate_back_color: 0xcc8f29  # 候选文字背景色
      hilited_comment_text_color: 0xffffff    # 注解文字高亮
      hilited_label_color: 0xffffff           # 已选字的数字的颜色
      label_color: 0x888888                   # 预选栏编号颜色

    solarized_rock:
      name: 日光石
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 6                             # 窗口圆角 
      font_point: 16                               # 候选文字大小
      label_font_point: 15                         # 候选编号大小
      line_spacing: 10                             # 行间距(适用于竖排)
      font_face: "PingFangSC-Regular,HanaMinB"     # 候选词字体
      text_color: 0x8236d3                     # 拼音行文字颜色
      back_color: 0x362b00                     # 候选条背景色，24位色值，16进制，BGR顺序
      candidate_text_color: 0x969483           # 预选项文字颜色
      comment_text_color: 0xc098a12a           # 拼音等提示文字颜色
      hilited_text_color: 0x98a12a             # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0x444444             # 第一候选项背景背景色
      hilited_candidate_label_color: 0xfafafa  # 第一候选项编号颜色
      hilited_candidate_back_color: 0x8236d3   # 候选文字背景色
      hilited_candidate_text_color: 0xffffff   # 第一候选项文字颜色
      hilited_comment_text_color: 0x362b00     # 注解文字高亮  

    solarized_dark:
      name: 夜光石
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 6                             # 窗口圆角 
      font_point: 16                               # 候选文字大小
      label_font_point: 15                         # 候选编号大小
      line_spacing: 10                             # 行间距(适用于竖排)
      font_face: "PingFangSC-Regular,HanaMinB"     # 候选词字体
      text_color: 0xA1A095                     # 拼音行文字颜色
      border_color: 0xf02A1F00                 # 边框颜色
      label_color: 0xCC8947                    # 预选栏编号颜色
      back_color: 0xf0352A0A                   # 候选条背景色，24位色值，16进制，BGR顺序
      candidate_text_color: 0x989F52           # 预选项文字颜色
      comment_text_color: 0x289989             # 拼音等提示文字颜色
      hilited_text_color: 0x2C8BAE             # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0x444444             # 第一候选项背景背景色
      hilited_candidate_label_color: 0x2566C6  # 第一候选项编号颜色
      hilited_candidate_back_color: 0xD7E8ED   # 候选文字背景色
      hilited_candidate_text_color: 0x3942CB   # 第一候选项文字颜色
      hilited_comment_text_color: 0x8144C2     # 注解文字高亮         

    apathy:
      name: 冷漠
      horizontal: true               # true横排，false竖排
      back_color: 0xFFFFFF           # 候选条背景色，24位色值，16进制，BGR顺序
      border_height: 0               # 窗口上下高度，大于圆角半径才生效
      border_width: 8                # 窗口左右宽度
      line_spacing: 10               # 行间距(适用于竖排)
      candidate_format: "%c %@ "     # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      comment_text_color: 0x999999              # 拼音等提示文字颜色
      corner_radius: 5                          # 窗口圆角
      font_point: 17                            # 候选文字大小
      hilited_candidate_back_color: 0xFFF0E4    # 候选文字背景色
      hilited_candidate_text_color: 0xEE6E00    # 第一候选项文字颜色
      inline_preedit: true           # 拼音位于： 候选框 false | 行内 true
      label_font_point: 12           # 候选编号大小
      text_color: 0x424242           # 拼音行文字颜色

    google:
      name: 谷歌
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 15                     # 候选编号大小
      corner_radius: 6                         # 窗口圆角
      line_spacing: 10                         # 行间距(适用于竖排)
      text_color: 0x666666                     # 拼音行文字颜色
      candidate_text_color: 0x000000           # 预选项文字颜色
      back_color: 0xFFFFFF                     # 候选条背景色
      border_color: 0xE2E2E2                   # 边框
      hilited_text_color: 0x000000             # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0xFFFFFF             # 第一候选项背景背景色
      hilited_candidate_text_color: 0xffffff   # 第一候选项文字颜色
      hilited_candidate_back_color: 0xCE7539   # 候选文字背景色 
      comment_text_color: 0x6D6D6D             # 拼音等提示文字颜色
      hilited_comment_text_color: 0xEBC6B0     # 注解文字高亮
      hilited_candidate_label_color: 0xfafafa  # 第一候选项编号颜色

    milan:
      name: 米兰
      horizontal: false              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 14                     # 候选编号大小
      line_spacing: 10                         # 行间距(适用于竖排)
      border_height: 4                         # 窗口上下高度，大于圆角半径才生效
      border_width: 4                          # 窗口左右宽度，大于圆角半径才生效
      corner_radius: 5                         # 窗口圆角
      back_color: 0xFFFFFF                     # 候选条背景色
      comment_text_color: 0x999999             # 拼音等提示文字颜色
      hilited_candidate_back_color: 0xF5803B   # 候选文字背景色
      hilited_candidate_text_color: 0xFFFFFF   # 第一候选项文字颜色
      text_color: 0x424242                     # 拼音行文字颜色

    ink:
      name: 墨池
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 14                     # 候选编号大小
      corner_radius: 5                         # 窗口圆角
      line_spacing: 10                         # 行间距(适用于竖排)
      text_color: 0x5a5a5a                     # 拼音等提示文字颜色
      back_color: 0xeeffffff                   # 候选条背景色
      candidate_text_color: 0x000000           # 第一候选项文字颜色
      hilited_text_color: 0x000000             # 高亮拼音 (需要开启内嵌编码)
      hilited_candidate_text_color: 0xffffff   # 第一候选项文字颜色
      hilited_candidate_back_color: 0xcc000000 # 候选文字背景色
      comment_text_color: 0x5a5a5a             # 拼音等提示文字颜色
      hilited_comment_text_color: 0x808080     # 注解文字高亮

    purity:
      name: 纯洁
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 14                     # 候选编号大小
      corner_radius: 5                         # 窗口圆角
      line_spacing: 10                         # 行间距(适用于竖排)
      text_color: 0xc2c2c2                     # 拼音等提示文字颜色
      back_color: 0x444444                     # 候选条背景色
      candidate_text_color: 0xeeeeee           # 第一候选项文字颜色
      hilited_text_color: 0xeeeeee             # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0x444444             # 第一候选项背景背景色
      hilited_candidate_text_color: 0x000000   # 第一候选项文字颜色
      hilited_candidate_back_color: 0xfafafa   # 候选文字背景色
      comment_text_color: 0x808080             # 拼音等提示文字颜色

    starcraft:
      name: 星际争霸
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 14                     # 候选编号大小
      corner_radius: 5                         # 窗口圆角
      line_spacing: 10                         # 行间距(适用于竖排)
      text_color: 0xccaa88                     # 拼音等提示文字颜色
      candidate_text_color: 0x30bb55           # 第一候选项文字颜色
      back_color: 0xee000000                   # 候选条背景色
      border_color: 0x1010a0                   # 边框色
      hilited_text_color: 0xfecb96             # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0x000000             # 第一候选项背景背景色
      hilited_candidate_text_color: 0x70ffaf   # 第一候选项文字颜色
      hilited_candidate_back_color: 0x000000   # 候选文字背景色
      comment_text_color: 0x1010d0             # 拼音等提示文字颜色
      hilited_comment_text_color: 0x1010f0     # 注解文字高亮

    nord_light:
      name: 北方浅色
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 14                     # 候选编号大小
      corner_radius: 5                         # 窗口圆角
      line_spacing: 10                         # 行间距(适用于竖排)
      back_color: 0xF4EFEC                     # 候选条背景色
      border_color: 0xF4EFEC                   # 边框色
      candidate_text_color: 0xC1A181           # 第一候选项文字颜色
      comment_text_color: 0xD0C088             # 拼音等提示文字颜色
      hilited_back_color: 0xF0E9E5             # 第一候选项背景背景色
      hilited_candidate_back_color: 0xE9DED8   # 候选文字背景色
      hilited_candidate_text_color: 0xAC815E   # 第一候选项文字颜色
      hilited_text_color: 0xAD8EB4             # 高亮拼音 (需要开启内嵌编码)
      text_color: 0x7087D0                     # 拼音等提示文字颜色

    nord_dark:
      name: 北方深色
      horizontal: true              # true横排，false竖排
      candidate_format: "%c %@ "    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      font_point: 16                           # 候选文字大小
      label_font_point: 14                     # 候选编号大小
      corner_radius: 5                         # 窗口圆角
      line_spacing: 10                         # 行间距(适用于竖排)
      back_color: 0x473A33                     # 候选条背景色
      border_color: 0x473A33                   # 边框色
      candidate_text_color: 0xF5D887           # 第一候选项文字颜色
      comment_text_color: 0xE6B687             # 拼音等提示文字颜色
      hilited_back_color: 0x473A33             # 第一候选项背景背景色
      hilited_candidate_back_color: 0x5D4C43   # 候选文字背景色
      hilited_candidate_text_color: 0xC0E077   # 第一候选项文字颜色
      hilited_text_color: 0x6EC8F5             # 高亮拼音 (需要开启内嵌编码)
      text_color: 0x78E8F0                     # 拼音等提示文字颜色
  
  # 特定App默认中/英文输入, 以及中文状态默认输出英文标点
  app_options:
    # com.apple.Spotlight: # 聚焦搜索
    #   ascii_mode: false             # false默认英文,false默认中文
    # com.runningwithcrayons.Alfred: # alfred
    #   ascii_mode: false
    # com.tencent.Lemon: # 腾讯柠檬
    #   ascii_mode: false
    # com.apple.dt.Xcode: # Xcode
    #   ascii_mode: false
    # com.nektony.App-Cleaner-SII: # App Cleaner & Uninstaller
    #   ascii_mode: false
    # com.xunyong.hapigo: # hapigo
    #   ascii_mode: false
    # com.raycast.macos: # Raycast
    #   ascii_mode: false
    com.apple.Terminal: # 终端
      ascii_mode: true
    com.termius-dmg.mac: # termius
      ascii_mode: true
    com.microsoft.VSCode: # Visual Studio Code
      ascii_mode: false            # 默认就为False
      ascii_punct: true            # 中文状态输出英文标点(半角)
    com.jetbrains.intellij: # idea
      ascii_punct: true
    com.jetbrains.pycharm: # pycharm
      ascii_punct: true
    com.jetbrains.CLion: # clion
      ascii_punct: true
    com.todesktop.230313mzl4w4u92：
      ascii_punct: true
```

以上是我的squirrel.custom.yaml文件，在更新到最新版本:1.0.2之后，  app_options中的ascii_punct设置都不生效了，另外皮肤也没生效，会切换到squirrel.yaml中的配置，请问是BUG吗？

- MacOS Version：14.6.1

- Squirrel Version：1.0.2

- 雾凇词库
